// A century of American chart hits, roughly 1926 to 2025.
//
// This is a curated selection of songs that topped or defined Billboard's
// charts, not a copy of the charts themselves — the Hot 100 only began in
// August 1958, so everything before that comes from Billboard's earlier
// best-seller and jukebox charts. Years are the year the recording came out,
// which is what the game asks players to place. Where a single crossed a new
// year on its way up the chart, the release year wins.
//
// Pre-1960s entries are the thinnest on streaming: a recording with no
// authorised preview is quietly retired before anyone draws it, so the deck
// simply plays a little shorter rather than breaking a turn.

export const BILLBOARD_SONGS = [
  // ---------- 1926-1939 ----------
  { title: 'Bye Bye Blackbird', artist: 'Gene Austin', year: 1926 },
  { title: 'My Blue Heaven', artist: 'Gene Austin', year: 1927 },
  { title: "Ol' Man River", artist: 'Paul Robeson', year: 1928 },
  { title: 'Makin’ Whoopee', artist: 'Eddie Cantor', year: 1928 },
  { title: "Singin' in the Rain", artist: 'Cliff Edwards', year: 1929 },
  { title: "Ain't Misbehavin'", artist: 'Louis Armstrong', year: 1929 },
  { title: "Puttin' On the Ritz", artist: 'Harry Richman', year: 1930 },
  { title: 'Minnie the Moocher', artist: 'Cab Calloway', year: 1931 },
  { title: 'Brother, Can You Spare a Dime?', artist: 'Bing Crosby', year: 1932 },
  { title: 'Stormy Weather', artist: 'Ethel Waters', year: 1933 },
  { title: 'Cheek to Cheek', artist: 'Fred Astaire', year: 1935 },
  { title: 'Pennies from Heaven', artist: 'Bing Crosby', year: 1936 },
  { title: 'Sing, Sing, Sing', artist: 'Benny Goodman', year: 1937 },
  { title: 'Begin the Beguine', artist: 'Artie Shaw', year: 1938 },
  { title: 'Over the Rainbow', artist: 'Judy Garland', year: 1939 },
  { title: 'Strange Fruit', artist: 'Billie Holiday', year: 1939 },
  { title: 'In the Mood', artist: 'Glenn Miller', year: 1939 },

  // ---------- 1940s ----------
  { title: 'Frenesi', artist: 'Artie Shaw', year: 1940 },
  { title: 'Chattanooga Choo Choo', artist: 'Glenn Miller', year: 1941 },
  { title: 'Boogie Woogie Bugle Boy', artist: 'The Andrews Sisters', year: 1941 },
  { title: 'White Christmas', artist: 'Bing Crosby', year: 1942 },
  { title: 'Paper Doll', artist: 'The Mills Brothers', year: 1943 },
  { title: "I'll Be Seeing You", artist: 'Bing Crosby', year: 1944 },
  { title: 'Sentimental Journey', artist: 'Doris Day', year: 1945 },
  { title: 'Rum and Coca-Cola', artist: 'The Andrews Sisters', year: 1945 },
  { title: 'Prisoner of Love', artist: 'Perry Como', year: 1946 },
  { title: 'Nature Boy', artist: 'Nat King Cole', year: 1948 },
  { title: 'Buttons and Bows', artist: 'Dinah Shore', year: 1948 },
  { title: 'Riders in the Sky', artist: 'Vaughn Monroe', year: 1949 },
  { title: 'Some Enchanted Evening', artist: 'Perry Como', year: 1949 },
  { title: 'Rudolph the Red-Nosed Reindeer', artist: 'Gene Autry', year: 1949 },

  // ---------- 1950s ----------
  { title: 'Goodnight, Irene', artist: 'The Weavers', year: 1950 },
  { title: 'Mona Lisa', artist: 'Nat King Cole', year: 1950 },
  { title: 'Cry', artist: 'Johnnie Ray', year: 1951 },
  { title: "Your Cheatin' Heart", artist: 'Hank Williams', year: 1953 },
  { title: 'Vaya con Dios', artist: 'Les Paul & Mary Ford', year: 1953 },
  { title: 'Sh-Boom', artist: 'The Crew-Cuts', year: 1954 },
  { title: 'Mr. Sandman', artist: 'The Chordettes', year: 1954 },
  { title: 'Rock Around the Clock', artist: 'Bill Haley & His Comets', year: 1955 },
  { title: 'Cherry Pink and Apple Blossom White', artist: 'Perez Prado', year: 1955 },
  { title: "Ain't That a Shame", artist: 'Fats Domino', year: 1955 },
  { title: 'Heartbreak Hotel', artist: 'Elvis Presley', year: 1956 },
  { title: 'Hound Dog', artist: 'Elvis Presley', year: 1956 },
  { title: 'Blue Suede Shoes', artist: 'Carl Perkins', year: 1956 },
  { title: 'Long Tall Sally', artist: 'Little Richard', year: 1956 },
  { title: 'All Shook Up', artist: 'Elvis Presley', year: 1957 },
  { title: 'Jailhouse Rock', artist: 'Elvis Presley', year: 1957 },
  { title: 'Wake Up Little Susie', artist: 'The Everly Brothers', year: 1957 },
  { title: 'Great Balls of Fire', artist: 'Jerry Lee Lewis', year: 1957 },
  { title: "That'll Be the Day", artist: 'The Crickets', year: 1957 },
  { title: 'Johnny B. Goode', artist: 'Chuck Berry', year: 1958 },
  { title: 'At the Hop', artist: 'Danny & The Juniors', year: 1958 },
  { title: 'Yakety Yak', artist: 'The Coasters', year: 1958 },
  { title: 'Mack the Knife', artist: 'Bobby Darin', year: 1959 },
  { title: 'Personality', artist: 'Lloyd Price', year: 1959 },
  { title: 'Put Your Head on My Shoulder', artist: 'Paul Anka', year: 1959 },
  { title: "What'd I Say", artist: 'Ray Charles', year: 1959 },

  // ---------- 1960s ----------
  { title: 'The Twist', artist: 'Chubby Checker', year: 1960 },
  { title: "Cathy's Clown", artist: 'The Everly Brothers', year: 1960 },
  { title: "It's Now or Never", artist: 'Elvis Presley', year: 1960 },
  { title: 'Georgia on My Mind', artist: 'Ray Charles', year: 1960 },
  { title: 'Stand by Me', artist: 'Ben E. King', year: 1961 },
  { title: 'Runaway', artist: 'Del Shannon', year: 1961 },
  { title: 'Please Mr. Postman', artist: 'The Marvelettes', year: 1961 },
  { title: "I Can't Stop Loving You", artist: 'Ray Charles', year: 1962 },
  { title: 'Sherry', artist: 'The Four Seasons', year: 1962 },
  { title: "Surfin' U.S.A.", artist: 'The Beach Boys', year: 1963 },
  { title: 'Be My Baby', artist: 'The Ronettes', year: 1963 },
  { title: 'Louie Louie', artist: 'The Kingsmen', year: 1963 },
  { title: 'I Want to Hold Your Hand', artist: 'The Beatles', year: 1964 },
  { title: 'Oh, Pretty Woman', artist: 'Roy Orbison', year: 1964 },
  { title: 'The House of the Rising Sun', artist: 'The Animals', year: 1964 },
  { title: 'My Girl', artist: 'The Temptations', year: 1964 },
  { title: "(I Can't Get No) Satisfaction", artist: 'The Rolling Stones', year: 1965 },
  { title: 'Like a Rolling Stone', artist: 'Bob Dylan', year: 1965 },
  { title: 'Help!', artist: 'The Beatles', year: 1965 },
  { title: "California Dreamin'", artist: 'The Mamas & The Papas', year: 1965 },
  { title: 'Good Vibrations', artist: 'The Beach Boys', year: 1966 },
  { title: 'These Boots Are Made for Walkin’', artist: 'Nancy Sinatra', year: 1966 },
  { title: 'Paint It Black', artist: 'The Rolling Stones', year: 1966 },
  { title: 'Light My Fire', artist: 'The Doors', year: 1967 },
  { title: 'Respect', artist: 'Aretha Franklin', year: 1967 },
  { title: 'Somebody to Love', artist: 'Jefferson Airplane', year: 1967 },
  { title: 'Hey Jude', artist: 'The Beatles', year: 1968 },
  { title: '(Sittin’ On) The Dock of the Bay', artist: 'Otis Redding', year: 1968 },
  { title: 'Born to Be Wild', artist: 'Steppenwolf', year: 1968 },
  { title: 'Sugar, Sugar', artist: 'The Archies', year: 1969 },
  { title: 'Suspicious Minds', artist: 'Elvis Presley', year: 1969 },

  // ---------- 1970s ----------
  { title: 'Bridge Over Troubled Water', artist: 'Simon & Garfunkel', year: 1970 },
  { title: 'Let It Be', artist: 'The Beatles', year: 1970 },
  { title: 'ABC', artist: 'The Jackson 5', year: 1970 },
  { title: 'Imagine', artist: 'John Lennon', year: 1971 },
  { title: "What's Going On", artist: 'Marvin Gaye', year: 1971 },
  { title: 'Maggie May', artist: 'Rod Stewart', year: 1971 },
  { title: 'American Pie', artist: 'Don McLean', year: 1971 },
  { title: 'Lean on Me', artist: 'Bill Withers', year: 1972 },
  { title: 'Superstition', artist: 'Stevie Wonder', year: 1972 },
  { title: 'Killing Me Softly with His Song', artist: 'Roberta Flack', year: 1973 },
  { title: 'Tie a Yellow Ribbon Round the Ole Oak Tree', artist: 'Tony Orlando & Dawn', year: 1973 },
  { title: 'Dream On', artist: 'Aerosmith', year: 1973 },
  { title: 'Waterloo', artist: 'ABBA', year: 1974 },
  { title: 'The Way We Were', artist: 'Barbra Streisand', year: 1974 },
  { title: 'Bohemian Rhapsody', artist: 'Queen', year: 1975 },
  { title: 'Love Will Keep Us Together', artist: 'Captain & Tennille', year: 1975 },
  { title: 'Fame', artist: 'David Bowie', year: 1975 },
  { title: 'Dancing Queen', artist: 'ABBA', year: 1976 },
  { title: 'Hotel California', artist: 'Eagles', year: 1976 },
  { title: 'Play That Funky Music', artist: 'Wild Cherry', year: 1976 },
  { title: "Stayin' Alive", artist: 'Bee Gees', year: 1977 },
  { title: 'I Will Survive', artist: 'Gloria Gaynor', year: 1978 },
  { title: 'Night Fever', artist: 'Bee Gees', year: 1978 },
  { title: 'Le Freak', artist: 'Chic', year: 1978 },
  { title: 'Y.M.C.A.', artist: 'Village People', year: 1978 },
  { title: 'My Sharona', artist: 'The Knack', year: 1979 },
  { title: 'Good Times', artist: 'Chic', year: 1979 },
  { title: "Don't Stop 'Til You Get Enough", artist: 'Michael Jackson', year: 1979 },
  { title: "Rapper's Delight", artist: 'The Sugarhill Gang', year: 1979 },

  // ---------- 1980s ----------
  { title: 'Another One Bites the Dust', artist: 'Queen', year: 1980 },
  { title: 'Call Me', artist: 'Blondie', year: 1980 },
  { title: 'Bette Davis Eyes', artist: 'Kim Carnes', year: 1981 },
  { title: 'Physical', artist: 'Olivia Newton-John', year: 1981 },
  { title: 'Under Pressure', artist: 'Queen & David Bowie', year: 1981 },
  { title: 'Eye of the Tiger', artist: 'Survivor', year: 1982 },
  { title: 'Billie Jean', artist: 'Michael Jackson', year: 1983 },
  { title: 'Every Breath You Take', artist: 'The Police', year: 1983 },
  { title: 'Sweet Dreams (Are Made of This)', artist: 'Eurythmics', year: 1983 },
  { title: "Let's Dance", artist: 'David Bowie', year: 1983 },
  { title: 'When Doves Cry', artist: 'Prince', year: 1984 },
  { title: 'Like a Virgin', artist: 'Madonna', year: 1984 },
  { title: 'Careless Whisper', artist: 'George Michael', year: 1984 },
  { title: 'We Are the World', artist: 'USA for Africa', year: 1985 },
  { title: 'Money for Nothing', artist: 'Dire Straits', year: 1985 },
  { title: 'Take On Me', artist: 'a-ha', year: 1985 },
  { title: "Papa Don't Preach", artist: 'Madonna', year: 1986 },
  { title: 'Walk Like an Egyptian', artist: 'The Bangles', year: 1986 },
  { title: "Livin' on a Prayer", artist: 'Bon Jovi', year: 1986 },
  { title: 'Faith', artist: 'George Michael', year: 1987 },
  { title: 'Never Gonna Give You Up', artist: 'Rick Astley', year: 1987 },
  { title: 'With or Without You', artist: 'U2', year: 1987 },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
  { title: 'Pour Some Sugar on Me', artist: 'Def Leppard', year: 1987 },
  { title: 'Straight Outta Compton', artist: 'N.W.A', year: 1988 },
  { title: 'Every Rose Has Its Thorn', artist: 'Poison', year: 1988 },
  { title: 'Fight the Power', artist: 'Public Enemy', year: 1989 },
  { title: 'Like a Prayer', artist: 'Madonna', year: 1989 },
  { title: 'Love Shack', artist: "The B-52's", year: 1989 },

  // ---------- 1990s ----------
  { title: 'Nothing Compares 2 U', artist: "Sinéad O'Connor", year: 1990 },
  { title: 'Ice Ice Baby', artist: 'Vanilla Ice', year: 1990 },
  { title: "U Can't Touch This", artist: 'MC Hammer', year: 1990 },
  { title: 'Smells Like Teen Spirit', artist: 'Nirvana', year: 1991 },
  { title: '(Everything I Do) I Do It for You', artist: 'Bryan Adams', year: 1991 },
  { title: 'Losing My Religion', artist: 'R.E.M.', year: 1991 },
  { title: 'Jump', artist: 'Kris Kross', year: 1992 },
  { title: 'I Will Always Love You', artist: 'Whitney Houston', year: 1992 },
  { title: 'Baby Got Back', artist: 'Sir Mix-a-Lot', year: 1992 },
  { title: 'Whoomp! (There It Is)', artist: 'Tag Team', year: 1993 },
  { title: 'Dreamlover', artist: 'Mariah Carey', year: 1993 },
  { title: 'Juicy', artist: 'The Notorious B.I.G.', year: 1994 },
  { title: 'Creep', artist: 'TLC', year: 1994 },
  { title: 'Waterfalls', artist: 'TLC', year: 1995 },
  { title: "Gangsta's Paradise", artist: 'Coolio', year: 1995 },
  { title: 'Wonderwall', artist: 'Oasis', year: 1995 },
  { title: 'Killing Me Softly', artist: 'Fugees', year: 1996 },
  { title: 'Wannabe', artist: 'Spice Girls', year: 1996 },
  { title: 'MMMBop', artist: 'Hanson', year: 1997 },
  { title: 'Barbie Girl', artist: 'Aqua', year: 1997 },
  { title: "I'll Be Missing You", artist: 'Puff Daddy', year: 1997 },
  { title: 'Bitter Sweet Symphony', artist: 'The Verve', year: 1997 },
  { title: '...Baby One More Time', artist: 'Britney Spears', year: 1998 },
  { title: 'The Boy Is Mine', artist: 'Brandy & Monica', year: 1998 },
  { title: 'Believe', artist: 'Cher', year: 1998 },
  { title: 'No Scrubs', artist: 'TLC', year: 1999 },
  { title: 'Livin’ la Vida Loca', artist: 'Ricky Martin', year: 1999 },
  { title: 'Smooth', artist: 'Santana', year: 1999 },
  { title: 'Genie in a Bottle', artist: 'Christina Aguilera', year: 1999 },

  // ---------- 2000s ----------
  { title: 'Oops!... I Did It Again', artist: 'Britney Spears', year: 2000 },
  { title: 'Bye Bye Bye', artist: 'NSYNC', year: 2000 },
  { title: 'Yellow', artist: 'Coldplay', year: 2000 },
  { title: 'Beautiful Day', artist: 'U2', year: 2000 },
  { title: 'Complicated', artist: 'Avril Lavigne', year: 2002 },
  { title: 'Lose Yourself', artist: 'Eminem', year: 2002 },
  { title: 'Toxic', artist: 'Britney Spears', year: 2003 },
  { title: 'In Da Club', artist: '50 Cent', year: 2003 },
  { title: 'Crazy in Love', artist: 'Beyoncé', year: 2003 },
  { title: 'Hey Ya!', artist: 'OutKast', year: 2003 },
  { title: 'Yeah!', artist: 'Usher', year: 2004 },
  { title: 'Since U Been Gone', artist: 'Kelly Clarkson', year: 2004 },
  { title: 'Mr. Brightside', artist: 'The Killers', year: 2004 },
  { title: 'Hollaback Girl', artist: 'Gwen Stefani', year: 2005 },
  { title: 'Gold Digger', artist: 'Kanye West', year: 2005 },
  { title: 'Crazy', artist: 'Gnarls Barkley', year: 2006 },
  { title: 'SexyBack', artist: 'Justin Timberlake', year: 2006 },
  { title: "Hips Don't Lie", artist: 'Shakira', year: 2006 },
  { title: 'Umbrella', artist: 'Rihanna', year: 2007 },
  { title: 'Apologize', artist: 'OneRepublic', year: 2007 },
  { title: 'Low', artist: 'Flo Rida', year: 2007 },
  { title: 'Bleeding Love', artist: 'Leona Lewis', year: 2007 },
  { title: 'I Kissed a Girl', artist: 'Katy Perry', year: 2008 },
  { title: 'Single Ladies (Put a Ring on It)', artist: 'Beyoncé', year: 2008 },
  { title: 'Poker Face', artist: 'Lady Gaga', year: 2008 },
  { title: 'Viva la Vida', artist: 'Coldplay', year: 2008 },
  { title: 'Use Somebody', artist: 'Kings of Leon', year: 2008 },
  { title: 'Boom Boom Pow', artist: 'The Black Eyed Peas', year: 2009 },
  { title: 'I Gotta Feeling', artist: 'The Black Eyed Peas', year: 2009 },
  { title: 'Empire State of Mind', artist: 'JAY-Z', year: 2009 },

  // ---------- 2010s ----------
  { title: 'Rolling in the Deep', artist: 'Adele', year: 2010 },
  { title: 'Firework', artist: 'Katy Perry', year: 2010 },
  { title: 'Just the Way You Are', artist: 'Bruno Mars', year: 2010 },
  { title: 'Party Rock Anthem', artist: 'LMFAO', year: 2011 },
  { title: 'Someone Like You', artist: 'Adele', year: 2011 },
  { title: 'Somebody That I Used to Know', artist: 'Gotye', year: 2011 },
  { title: 'Call Me Maybe', artist: 'Carly Rae Jepsen', year: 2012 },
  { title: 'Gangnam Style', artist: 'PSY', year: 2012 },
  { title: 'Thrift Shop', artist: 'Macklemore & Ryan Lewis', year: 2012 },
  { title: 'Radioactive', artist: 'Imagine Dragons', year: 2012 },
  { title: 'Blurred Lines', artist: 'Robin Thicke', year: 2013 },
  { title: 'Get Lucky', artist: 'Daft Punk', year: 2013 },
  { title: 'Royals', artist: 'Lorde', year: 2013 },
  { title: 'Happy', artist: 'Pharrell Williams', year: 2013 },
  { title: 'All About That Bass', artist: 'Meghan Trainor', year: 2014 },
  { title: 'Shake It Off', artist: 'Taylor Swift', year: 2014 },
  { title: 'Uptown Funk', artist: 'Mark Ronson', year: 2014 },
  { title: 'Hello', artist: 'Adele', year: 2015 },
  { title: "Can't Feel My Face", artist: 'The Weeknd', year: 2015 },
  { title: 'Hotline Bling', artist: 'Drake', year: 2015 },
  { title: 'Closer', artist: 'The Chainsmokers', year: 2016 },
  { title: 'One Dance', artist: 'Drake', year: 2016 },
  { title: 'Despacito', artist: 'Luis Fonsi', year: 2017 },
  { title: 'Shape of You', artist: 'Ed Sheeran', year: 2017 },
  { title: 'Havana', artist: 'Camila Cabello', year: 2017 },
  { title: "God's Plan", artist: 'Drake', year: 2018 },
  { title: 'Thank U, Next', artist: 'Ariana Grande', year: 2018 },
  { title: 'Sicko Mode', artist: 'Travis Scott', year: 2018 },
  { title: 'Sunflower', artist: 'Post Malone', year: 2018 },
  { title: 'Old Town Road', artist: 'Lil Nas X', year: 2019 },
  { title: 'Bad Guy', artist: 'Billie Eilish', year: 2019 },
  { title: 'Señorita', artist: 'Shawn Mendes', year: 2019 },
  { title: 'Blinding Lights', artist: 'The Weeknd', year: 2019 },
  { title: 'Cruel Summer', artist: 'Taylor Swift', year: 2019 },

  // ---------- 2020s ----------
  { title: 'Levitating', artist: 'Dua Lipa', year: 2020 },
  { title: 'Heat Waves', artist: 'Glass Animals', year: 2020 },
  { title: 'Drivers License', artist: 'Olivia Rodrigo', year: 2021 },
  { title: 'Good 4 U', artist: 'Olivia Rodrigo', year: 2021 },
  { title: 'Stay', artist: 'The Kid LAROI', year: 2021 },
  { title: 'Montero (Call Me By Your Name)', artist: 'Lil Nas X', year: 2021 },
  { title: 'As It Was', artist: 'Harry Styles', year: 2022 },
  { title: 'About Damn Time', artist: 'Lizzo', year: 2022 },
  { title: 'Anti-Hero', artist: 'Taylor Swift', year: 2022 },
  { title: 'Kill Bill', artist: 'SZA', year: 2022 },
  { title: 'Flowers', artist: 'Miley Cyrus', year: 2023 },
  { title: 'Last Night', artist: 'Morgan Wallen', year: 2023 },
  { title: 'Espresso', artist: 'Sabrina Carpenter', year: 2024 },
  { title: 'Not Like Us', artist: 'Kendrick Lamar', year: 2024 },
  { title: 'Birds of a Feather', artist: 'Billie Eilish', year: 2024 },
  { title: "Texas Hold 'Em", artist: 'Beyoncé', year: 2024 },
  { title: 'Die With A Smile', artist: 'Lady Gaga', year: 2024 },
  { title: 'APT.', artist: 'ROSÉ', year: 2024 },
];
