// Name That Tune: Eminem catalogue snapshot (reviewed 2026-07-22).
// Source: https://everysongby.com/artists/eminem/
// Cross-checked against Eminem's official discography and public leak/archive reporting.
// Spoken skits/interludes, project-name placeholders, and entries without a confirmed
// Eminem vocal are excluded. Archive-only records stay visible but are not auto-searched
// because Deezer/iTunes cannot provide authorised previews for them.

const EMINEM_RELEASED_1 = [
  {"title":"313","artist":"Eminem","year":1996},
  {"title":"Backstabber","artist":"Eminem","year":1996},
  {"title":"Dumpin’","artist":"Parts Unknown","year":1996},
  {"title":"Infinite","artist":"Eminem","year":1996},
  {"title":"It’s O.K.","artist":"Eminem","year":1996},
  {"title":"Jealousy Woes II","artist":"Eminem","year":1996},
  {"title":"Maxine","artist":"Eminem","year":1996},
  {"title":"Never 2 Far","artist":"Eminem","year":1996},
  {"title":"Open Mic","artist":"Eminem","year":1996},
  {"title":"Searchin’","artist":"Eminem","year":1996},
  {"title":"Tonite","artist":"Eminem","year":1996},
  {"title":"Intro (Slim Shady)","artist":"Eminem","year":1997},
  {"title":"Just the Two of Us","artist":"Eminem","year":1997},
  {"title":"Low Down, Dirty","artist":"Eminem","year":1997},
  {"title":"Mommy","artist":"Eminem","year":1997},
  {"title":"Murder, Murder","artist":"Eminem","year":1997},
  {"title":"No One’s Iller","artist":"Eminem","year":1997},
  {"title":"Take the Whole World with Me","artist":"Outsidaz","year":1997},
  {"title":"3hree6ix5ive","artist":"Skam","year":1998},
  {"title":"5 Star Generals","artist":"Shabaam Sahdeeq, Skam, A.L. and Kwest Tha Madd Lad","year":1998},
  {"title":"Drastic Measures","artist":"Indigenous Tribe","year":1998},
  {"title":"Flawless Victory","artist":"Da Rabeez","year":1998},
  {"title":"Fuck Off","artist":"Kid Rock","year":1998},
  {"title":"Green and Gold","artist":"The Anonymous","year":1998},
  {"title":"Trife Thieves","artist":"Bizarre and Fuzz Scoota","year":1998},
  {"title":"We Shine","artist":"Da Ruckus","year":1998},
  {"title":"’97 Bonnie & Clyde","artist":"Eminem","year":1999},
  {"title":"Any Man","artist":"Eminem","year":1999},
  {"title":"As the World Turns","artist":"Eminem","year":1999},
  {"title":"Bad Guys Always Die","artist":"Eminem","year":1999},
  {"title":"Bad Influence","artist":"Eminem","year":1999},
  {"title":"Bad Meets Evil","artist":"Eminem","year":1999},
  {"title":"Brain Damage","artist":"Eminem","year":1999},
  {"title":"Busa Rhyme","artist":"Missy Elliott","year":1999},
  {"title":"Cum on Everybody","artist":"Eminem","year":1999},
  {"title":"Dead Wrong","artist":"The Notorious B.I.G.","year":1999},
  {"title":"Desperados","artist":"DJ Butter, Bugz, Proof and Almighty Dreadnaughtz","year":1999},
  {"title":"Forgot About Dre","artist":"Dr. Dre","year":1999},
  {"title":"Get You Mad","artist":"Eminem","year":1999},
  {"title":"Guilty Conscience","artist":"Eminem","year":1999},
  {"title":"Hazardous Youth (A Cappella)","artist":"Eminem","year":1999},
  {"title":"Hustlers & Hardcore","artist":"Domingo","year":1999},
  {"title":"If I Get Locked Up","artist":"Funkmaster Flex, Big Kap and Dr. Dre","year":1999},
  {"title":"If I Had","artist":"Eminem","year":1999},
  {"title":"I’m Shady","artist":"Eminem","year":1999},
  {"title":"Just Don’t Give a Fuck","artist":"Eminem","year":1999},
  {"title":"Murder, Murder (Remix)","artist":"Eminem","year":1999},
  {"title":"My Fault","artist":"Eminem","year":1999},
  {"title":"My Fault (Pizza Mix)","artist":"Eminem","year":1999},
  {"title":"My Name Is","artist":"Eminem","year":1999},
  {"title":"Nuttin’ to Do","artist":"Bad Meets Evil","year":1999},
  {"title":"Public Service Announcement","artist":"Eminem","year":1999},
  {"title":"Rock Bottom","artist":"Eminem","year":1999},
  {"title":"Role Model","artist":"Eminem","year":1999},
  {"title":"Scary Movies","artist":"Bad Meets Evil","year":1999},
  {"title":"Still Don’t Give a Fuck","artist":"Eminem","year":1999},
  {"title":"Stir Crazy","artist":"The Madd Rapper","year":1999},
  {"title":"The Anthem","artist":"Sway & King Tech, RZA, Tech N9ne, Xzibit, Pharoahe Monch, Kool G Rap, Jayo Felony, Chino XL and KRS-One","year":1999},
  {"title":"The Last Hit","artist":"The High & Mighty","year":1999},
  {"title":"The Watcher","artist":"Dr. Dre and Knoc-turn'al","year":1999},
  {"title":"Till Hell Freezes Over","artist":"Eminem","year":1999},
  {"title":"Watch Deez","artist":"Thirstin Howl III and DJ Spinna","year":1999},
  {"title":"What’s the Difference","artist":"Dr. Dre","year":1999},
  {"title":"You Must Be Crazy","artist":"DJ Rectangle","year":1999},
  {"title":"Amityville","artist":"Eminem","year":2000},
  {"title":"Bitch Please II","artist":"Eminem","year":2000},
  {"title":"Criminal","artist":"Eminem","year":2000},
  {"title":"Don't Approach Me","artist":"Xzibit","year":2000},
  {"title":"Drug Ballad","artist":"Eminem","year":2000},
  {"title":"I’m Back","artist":"Eminem","year":2000},
  {"title":"I Remember (Dedication to Whitey Ford)","artist":"D12","year":2000},
  {"title":"Kill You","artist":"Eminem","year":2000},
  {"title":"Kim","artist":"Eminem","year":2000},
  {"title":"Marshall Mathers","artist":"Eminem","year":2000},
  {"title":"Off the Wall","artist":"Redman","year":2000},
  {"title":"Public Service Announcement 2000","artist":"Eminem","year":2000},
  {"title":"Quitter","artist":"D12","year":2000},
  {"title":"Remember Me?","artist":"Eminem","year":2000},
  {"title":"Rush Ya Clique","artist":"Outsidaz","year":2000},
  {"title":"Shit on You","artist":"D12","year":2000},
  {"title":"Stan","artist":"Eminem","year":2000},
  {"title":"The Kids","artist":"Eminem","year":2000},
  {"title":"The Real Slim Shady","artist":"Eminem","year":2000},
  {"title":"The Way I Am","artist":"Eminem","year":2000},
  {"title":"Under the Influence","artist":"Eminem","year":2000},
  {"title":"Who Knew","artist":"Eminem","year":2000},
  {"title":"Criminal (Live — Up in Smoke Tour)","artist":"Eminem","year":2000},
  {"title":"Dead Wrong (Live — Up in Smoke Tour)","artist":"Eminem","year":2000},
  {"title":"Forgot About Dre (Live — Up in Smoke Tour)","artist":"Eminem","year":2000},
  {"title":"Kill You (Live — Up in Smoke Tour)","artist":"Eminem","year":2000},
  {"title":"Marshall Mathers (Live — Up in Smoke Tour)","artist":"Eminem","year":2000},
  {"title":"The Real Slim Shady (Live — Up in Smoke Tour)","artist":"Eminem","year":2000},
  {"title":"Under the Influence (Live — Up in Smoke Tour)","artist":"Eminem","year":2000},
  {"title":"What’s the Difference (Live — Up in Smoke Tour)","artist":"Eminem","year":2000},
  {"title":"Ain’t Nuttin’ but Music","artist":"D12","year":2001},
  {"title":"American Psycho","artist":"D12","year":2001},
  {"title":"Blow My Buzz","artist":"D12","year":2001},
  {"title":"Devil’s Night","artist":"D12","year":2001},
  {"title":"Fight Music","artist":"D12","year":2001},
  {"title":"Girls","artist":"D12","year":2001},
];

const EMINEM_RELEASED_2 = [
  {"title":"Instigator","artist":"D12","year":2001},
  {"title":"Nasty Mind","artist":"D12","year":2001},
  {"title":"Pimp Like Me","artist":"D12","year":2001},
  {"title":"Pistol Pistol","artist":"D12","year":2001},
  {"title":"Purple Pills","artist":"D12","year":2001},
  {"title":"Renegade","artist":"Jay-Z","year":2001},
  {"title":"Revelation","artist":"D12","year":2001},
  {"title":"Shit Can Happen","artist":"D12","year":2001},
  {"title":"That’s How","artist":"D12","year":2001},
  {"title":"These Drugs","artist":"D12","year":2001},
  {"title":"What If I Was White","artist":"Sticky Fingaz","year":2001},
  {"title":"What the Beat","artist":"Method Man, Royce da 5'9\" and DJ Clue","year":2001},
  {"title":"Words Are Weapons","artist":"D12","year":2001},
  {"title":"8 Mile","artist":"Eminem","year":2002},
  {"title":"Business","artist":"Eminem","year":2002},
  {"title":"Cleanin’ Out My Closet","artist":"Eminem","year":2002},
  {"title":"Curtains Close","artist":"Eminem","year":2002},
  {"title":"Drips","artist":"Eminem","year":2002},
  {"title":"Hailie’s Song","artist":"Eminem","year":2002},
  {"title":"Jimmy, Brian and Mike","artist":"Eminem","year":2002},
  {"title":"Lose Yourself","artist":"Eminem","year":2002},
  {"title":"Love Me","artist":"Eminem","year":2002},
  {"title":"My Dad’s Gone Crazy","artist":"Eminem","year":2002},
  {"title":"My Name","artist":"Xzibit and Nate Dogg","year":2002},
  {"title":"Rabbit Run","artist":"Eminem","year":2002},
  {"title":"Rap Game","artist":"Eminem","year":2002},
  {"title":"Rock City","artist":"Royce da 5'9\"","year":2002},
  {"title":"Say Goodbye Hollywood","artist":"Eminem","year":2002},
  {"title":"Say What You Say","artist":"Eminem","year":2002},
  {"title":"Serious","artist":"Promatic","year":2002},
  {"title":"Sing for the Moment","artist":"Eminem","year":2002},
  {"title":"Soldier","artist":"Eminem","year":2002},
  {"title":"Square Dance","artist":"Eminem","year":2002},
  {"title":"Stimulate","artist":"Eminem","year":2002},
  {"title":"Superman","artist":"Eminem","year":2002},
  {"title":"The Conspiracy Freestyle","artist":"Eminem","year":2002},
  {"title":"’Till I Collapse","artist":"Eminem","year":2002},
  {"title":"When the Music Stops","artist":"Eminem","year":2002},
  {"title":"White America","artist":"Eminem","year":2002},
  {"title":"Without Me","artist":"Eminem","year":2002},
  {"title":"911","artist":"Boo-Yaa T.R.I.B.E. and B-Real","year":2003},
  {"title":"Don’t Push Me","artist":"50 Cent","year":2003},
  {"title":"Freestyle","artist":"DJ Kay Slay","year":2003},
  {"title":"Go to Sleep","artist":"DMX and Obie Trice","year":2003},
  {"title":"Hands on You","artist":"Obie Trice","year":2003},
  {"title":"Lady","artist":"Obie Trice","year":2003},
  {"title":"My Club","artist":"Obie Trice","year":2003},
  {"title":"Outro (Cheers)","artist":"Obie Trice","year":2003},
  {"title":"Patiently Waiting","artist":"50 Cent","year":2003},
  {"title":"Shit Hits the Fan","artist":"Obie Trice and Dr. Dre","year":2003},
  {"title":"We All Die One Day","artist":"Obie Trice","year":2003},
  {"title":"40 Oz.","artist":"D12","year":2004},
  {"title":"6 in the Morning","artist":"D12","year":2004},
  {"title":"American Psycho II","artist":"D12","year":2004},
  {"title":"Ass Like That","artist":"Eminem","year":2004},
  {"title":"Big Weenie","artist":"Eminem","year":2004},
  {"title":"Bitch","artist":"D12","year":2004},
  {"title":"Black Cotton","artist":"2Pac, Kastro and Young Noble","year":2004},
  {"title":"Crazy in Love","artist":"Eminem","year":2004},
  {"title":"Encore / Curtains Down","artist":"Eminem","year":2004},
  {"title":"Evil Deeds","artist":"Eminem","year":2004},
  {"title":"Get My Gun","artist":"D12","year":2004},
  {"title":"Git Up","artist":"D12","year":2004},
  {"title":"Good Die Young","artist":"D12","year":2004},
  {"title":"How Come","artist":"D12","year":2004},
  {"title":"I'll Be Damned","artist":"D12","year":2004},
  {"title":"I'm Gone","artist":"DJ Kay Slay and Obie Trice","year":2004},
  {"title":"Just Lose It","artist":"Eminem","year":2004},
  {"title":"Keep Talkin'","artist":"D12","year":2004},
  {"title":"Leave Dat Boy Alone","artist":"D12","year":2004},
  {"title":"Like Toy Soldiers","artist":"Eminem","year":2004},
  {"title":"Liner #1","artist":"Eminem","year":2004},
  {"title":"Liner #2","artist":"Eminem","year":2004},
  {"title":"Liner #3","artist":"Eminem","year":2004},
  {"title":"Liner #4","artist":"Eminem","year":2004},
  {"title":"Love You More","artist":"Eminem","year":2004},
  {"title":"Loyalty","artist":"D12","year":2004},
  {"title":"Mockingbird","artist":"Eminem","year":2004},
  {"title":"Mosh","artist":"Eminem","year":2004},
  {"title":"My 1st Single","artist":"Eminem","year":2004},
  {"title":"My Band","artist":"D12","year":2004},
  {"title":"Never Enough","artist":"Eminem","year":2004},
  {"title":"One Day at a Time (Em's Version)","artist":"2Pac and Outlawz","year":2004},
  {"title":"One Shot 2 Shot","artist":"Eminem","year":2004},
  {"title":"Pale Moonlight","artist":"Strike","year":2004},
  {"title":"Puke","artist":"Eminem","year":2004},
  {"title":"Rain Man","artist":"Eminem","year":2004},
  {"title":"Ricky Ticky Toc","artist":"Eminem","year":2004},
  {"title":"Slow Your Roll","artist":"D12","year":2004},
  {"title":"Soldier Like Me","artist":"2Pac","year":2004},
  {"title":"Spend Some Time","artist":"Eminem","year":2004},
  {"title":"U R the One","artist":"D12","year":2004},
  {"title":"Warrior Part 2","artist":"Lloyd Banks","year":2004},
  {"title":"We as Americans","artist":"Eminem","year":2004},
  {"title":"We Just Came to Party","artist":"Young Zee","year":2004},
  {"title":"Welcome to D-Block","artist":"Jadakiss, Styles P and Sheek Louch","year":2004},
  {"title":"Yellow Brick Road","artist":"Eminem","year":2004},
  {"title":"Drama Setter","artist":"Obie Trice and Tony Yayo","year":2005},
  {"title":"Emulate","artist":"Obie Trice","year":2005},
  {"title":"FACK","artist":"Eminem","year":2005},
];

const EMINEM_RELEASED_3 = [
  {"title":"Gatman and Robbin","artist":"50 Cent","year":2005},
  {"title":"Hip Hop","artist":"Bizarre","year":2005},
  {"title":"It Has Been Said","artist":"The Notorious B.I.G., Obie Trice and Diddy","year":2005},
  {"title":"Lean Back (Remix)","artist":"Fat Joe, Lil Jon, Mase and Remy Ma","year":2005},
  {"title":"No More to Say","artist":"Trick-Trick and Proof","year":2005},
  {"title":"Off to Tijuana","artist":"Hush","year":2005},
  {"title":"Oil Can Harry","artist":"Proof","year":2005},
  {"title":"Shake That","artist":"Eminem","year":2005},
  {"title":"We Ain't","artist":"The Game","year":2005},
  {"title":"Welcome 2 Detroit","artist":"Trick-Trick","year":2005},
  {"title":"When I’m Gone","artist":"Eminem","year":2005},
  {"title":"Business (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Cleanin’ Out My Closet (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Drips (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Drug Ballad (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Fight Music (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Forgot About Dre (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Just Don’t Give a Fuck (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Kill You (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"My Dad’s Gone Crazy (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Pimp Like Me (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Purple Pills (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Sing for the Moment (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Soldier (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Square Dance (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Stan (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Superman (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"The Way I Am (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"When the Music Stops (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"White America (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"Without Me (Live — Anger Management Tour)","artist":"Eminem","year":2005},
  {"title":"40 Oz. (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Ass Like That (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Business (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Cleanin’ Out My Closet (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Evil Deeds (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Git Up (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Got Some Teeth (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"How Come (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Just Don’t Give a Fuck (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Just Lose It (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Kill You (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Like Dat (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Like Toy Soldiers (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Lose Yourself (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Mockingbird (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Mosh (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"My Band (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Puke (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Rain Man (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Rockstar (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Stan (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Stay ’Bout It (Aqua) (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"The Set Up (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"The Way I Am (Live from New York City)","artist":"Eminem","year":2005},
  {"title":"Jimmy Crack Corn","artist":"Eminem","year":2006},
  {"title":"No Apologies","artist":"Eminem","year":2006},
  {"title":"Public Enemy #1","artist":"Eminem","year":2006},
  {"title":"Shady Narcotics (Intro)","artist":"Eminem","year":2006},
  {"title":"Smack That","artist":"Akon","year":2006},
  {"title":"Stat Quo Intro","artist":"Stat Quo","year":2006},
  {"title":"There They Go","artist":"Obie Trice and Big Herk","year":2006},
  {"title":"The Re-Up","artist":"50 Cent","year":2006},
  {"title":"Trapped","artist":"Proof","year":2006},
  {"title":"We’re Back","artist":"Eminem","year":2006},
  {"title":"You Don’t Know","artist":"Eminem","year":2006},
  {"title":"I Can Be","artist":"Helleva","year":2007},
  {"title":"Peep Show","artist":"50 Cent","year":2007},
  {"title":"Pistol Poppin","artist":"Cashis","year":2007},
  {"title":"Touchdown","artist":"T.I.","year":2007},
  {"title":"Who Want It","artist":"Trick-Trick","year":2008},
  {"title":"3 a.m.","artist":"Eminem","year":2009},
  {"title":"Bagpipes from Baghdad","artist":"Eminem","year":2009},
  {"title":"Beautiful","artist":"Eminem","year":2009},
  {"title":"Buffalo Bill","artist":"Eminem","year":2009},
  {"title":"Careful What You Wish For","artist":"Eminem","year":2009},
  {"title":"Chemical Warfare","artist":"The Alchemist","year":2009},
  {"title":"Crack a Bottle","artist":"Eminem","year":2009},
  {"title":"Déjà Vu","artist":"Eminem","year":2009},
  {"title":"Drop the Bomb on ’Em","artist":"Eminem","year":2009},
  {"title":"Elevator","artist":"Eminem","year":2009},
  {"title":"Forever","artist":"Drake","year":2009},
  {"title":"Hell Breaks Loose","artist":"Eminem","year":2009},
  {"title":"Hello","artist":"Eminem","year":2009},
  {"title":"Insane","artist":"Eminem","year":2009},
  {"title":"Medicine Ball","artist":"Eminem","year":2009},
  {"title":"Music Box","artist":"Eminem","year":2009},
  {"title":"Must Be the Ganja","artist":"Eminem","year":2009},
  {"title":"My Darling","artist":"Eminem","year":2009},
  {"title":"My Mom","artist":"Eminem","year":2009},
  {"title":"Old Time’s Sake","artist":"Eminem","year":2009},
  {"title":"Psycho","artist":"50 Cent","year":2009},
  {"title":"Same Song & Dance","artist":"Eminem","year":2009},
  {"title":"Stay Wide Awake","artist":"Eminem","year":2009},
  {"title":"Taking My Ball","artist":"Eminem","year":2009},
  {"title":"Underground","artist":"Eminem","year":2009},
  {"title":"We Made You","artist":"Eminem","year":2009},
  {"title":"25 to Life","artist":"Eminem","year":2010},
  {"title":"Airplanes, Part II","artist":"B.o.B","year":2010},
  {"title":"Almost Famous","artist":"Eminem","year":2010},
];

const EMINEM_RELEASED_4 = [
  {"title":"Atlanta on Fire","artist":"Stat Quo","year":2010},
  {"title":"Cinderella Man","artist":"Eminem","year":2010},
  {"title":"Classic Shit","artist":"Stat Quo","year":2010},
  {"title":"Cold Wind Blows","artist":"Eminem","year":2010},
  {"title":"Drop the World","artist":"Lil Wayne","year":2010},
  {"title":"Going Through Changes","artist":"Eminem","year":2010},
  {"title":"Love the Way You Lie","artist":"Eminem","year":2010},
  {"title":"Love the Way You Lie (Part II)","artist":"Rihanna","year":2010},
  {"title":"No Love","artist":"Eminem","year":2010},
  {"title":"Not Afraid","artist":"Eminem","year":2010},
  {"title":"On Fire","artist":"Eminem","year":2010},
  {"title":"Ridaz","artist":"Eminem","year":2010},
  {"title":"Roman’s Revenge","artist":"Nicki Minaj","year":2010},
  {"title":"Seduction","artist":"Eminem","year":2010},
  {"title":"Session One","artist":"Eminem","year":2010},
  {"title":"So Bad","artist":"Eminem","year":2010},
  {"title":"Space Bound","artist":"Eminem","year":2010},
  {"title":"Talkin’ 2 Myself","artist":"Eminem","year":2010},
  {"title":"That’s All She Wrote","artist":"T.I.","year":2010},
  {"title":"Untitled","artist":"Eminem","year":2010},
  {"title":"Won’t Back Down","artist":"Eminem","year":2010},
  {"title":"W.T.P.","artist":"Eminem","year":2010},
  {"title":"You’re Never Over","artist":"Eminem","year":2010},
  {"title":"Where I’m At","artist":"Lloyd Banks","year":2010},
  {"title":"Above the Law","artist":"Bad Meets Evil","year":2011},
  {"title":"A Kiss","artist":"Bad Meets Evil","year":2011},
  {"title":"Echo","artist":"Bad Meets Evil","year":2011},
  {"title":"Fast Lane","artist":"Bad Meets Evil","year":2011},
  {"title":"I’m on Everything","artist":"Bad Meets Evil","year":2011},
  {"title":"I Need a Doctor","artist":"Dr. Dre and Skylar Grey","year":2011},
  {"title":"Lighters","artist":"Bad Meets Evil","year":2011},
  {"title":"Living Proof","artist":"Bad Meets Evil","year":2011},
  {"title":"Loud Noises","artist":"Bad Meets Evil","year":2011},
  {"title":"Take from Me","artist":"Bad Meets Evil","year":2011},
  {"title":"The Reunion","artist":"Bad Meets Evil","year":2011},
  {"title":"Things Get Worse","artist":"B.o.B","year":2011},
  {"title":"Throw It Up","artist":"Yelawolf and Gangsta Boo","year":2011},
  {"title":"Welcome 2 Hell","artist":"Bad Meets Evil","year":2011},
  {"title":"Writer's Block","artist":"Royce da 5'9\"","year":2011},
  {"title":"In This World","artist":"Yelawolf","year":2011},
  {"title":"Asylum","artist":"Slaughterhouse","year":2012},
  {"title":"C'mon Let Me Ride","artist":"Skylar Grey","year":2012},
  {"title":"Here Comes the Weekend","artist":"P!nk","year":2012},
  {"title":"My Life","artist":"50 Cent","year":2012},
  {"title":"Numb","artist":"Rihanna","year":2012},
  {"title":"Our House","artist":"Slaughterhouse and Skylar Grey","year":2012},
  {"title":"Richard","artist":"Obie Trice","year":2012},
  {"title":"Throw That","artist":"Slaughterhouse","year":2012},
  {"title":"Asshole","artist":"Eminem","year":2013},
  {"title":"Baby","artist":"Eminem","year":2013},
  {"title":"Bad Guy","artist":"Eminem","year":2013},
  {"title":"Beautiful Pain","artist":"Eminem","year":2013},
  {"title":"Berzerk","artist":"Eminem","year":2013},
  {"title":"Brainless","artist":"Eminem","year":2013},
  {"title":"Desperation","artist":"Eminem","year":2013},
  {"title":"Don’t Front","artist":"Eminem","year":2013},
  {"title":"Evil Twin","artist":"Eminem","year":2013},
  {"title":"Groundhog Day","artist":"Eminem","year":2013},
  {"title":"Headlights","artist":"Eminem","year":2013},
  {"title":"Legacy","artist":"Eminem","year":2013},
  {"title":"Love Game","artist":"Eminem","year":2013},
  {"title":"Rap God","artist":"Eminem","year":2013},
  {"title":"Rhyme or Reason","artist":"Eminem","year":2013},
  {"title":"So Far…","artist":"Eminem","year":2013},
  {"title":"So Much Better","artist":"Eminem","year":2013},
  {"title":"Stronger Than I Was","artist":"Eminem","year":2013},
  {"title":"Survival","artist":"Eminem","year":2013},
  {"title":"Symphony in H","artist":"Tony Touch","year":2013},
  {"title":"The Monster","artist":"Eminem","year":2013},
  {"title":"Wicked Ways","artist":"Eminem","year":2013},
  {"title":"Calm Down","artist":"Busta Rhymes","year":2014},
  {"title":"Detroit vs. Everybody","artist":"Eminem","year":2014},
  {"title":"Die Alone","artist":"Eminem","year":2014},
  {"title":"Fine Line","artist":"Eminem","year":2014},
  {"title":"Guts Over Fear","artist":"Eminem","year":2014},
  {"title":"Lose Yourself (Demo Version)","artist":"Eminem","year":2014},
  {"title":"Psychopath Killer","artist":"Slaughterhouse and Yelawolf","year":2014},
  {"title":"Right for Me","artist":"Eminem","year":2014},
  {"title":"Shady Classics Intro","artist":"Eminem","year":2014},
  {"title":"ShadyXV","artist":"Eminem","year":2014},
  {"title":"Twerk Dat Pop That","artist":"Trick-Trick and Royce da 5'9\"","year":2014},
  {"title":"Twisted","artist":"Skylar Grey and Yelawolf","year":2014},
  {"title":"Vegas","artist":"Bad Meets Evil","year":2014},
  {"title":"All I Think About","artist":"Bad Meets Evil","year":2015},
  {"title":"Best Friend","artist":"Yelawolf","year":2015},
  {"title":"Kings Never Die","artist":"Eminem","year":2015},
  {"title":"Medicine Man","artist":"Dr. Dre","year":2015},
  {"title":"Phenomenal","artist":"Eminem","year":2015},
  {"title":"Raw","artist":"Bad Meets Evil","year":2015},
  {"title":"Speedom (Worldwide Choppers 2)","artist":"Tech N9ne and Krizz Kaliko","year":2015},
  {"title":"The Hills (Eminem Remix)","artist":"The Weeknd","year":2015},
  {"title":"The Intro and Em","artist":"D12","year":2015},
  {"title":"Campaign Speech","artist":"Eminem","year":2016},
  {"title":"Infinite (F.B.T. Remix)","artist":"Eminem","year":2016},
  {"title":"Kill for You","artist":"Skylar Grey","year":2016},
  {"title":"Welcome to Planet X (We're Coming for You)","artist":"KXNG Crooked","year":2016},
  {"title":"Arose","artist":"Eminem","year":2017},
  {"title":"Bad Husband","artist":"Eminem","year":2017},
  {"title":"Believe","artist":"Eminem","year":2017},
  {"title":"Castle","artist":"Eminem","year":2017},
];

const EMINEM_RELEASED_5 = [
  {"title":"Chloraseptic","artist":"Eminem","year":2017},
  {"title":"Chloraseptic (Remix)","artist":"Eminem","year":2017},
  {"title":"Framed","artist":"Eminem","year":2017},
  {"title":"Heat","artist":"Eminem","year":2017},
  {"title":"In Your Head","artist":"Eminem","year":2017},
  {"title":"Like Home","artist":"Eminem","year":2017},
  {"title":"Need Me","artist":"Eminem","year":2017},
  {"title":"No Favors","artist":"Big Sean","year":2017},
  {"title":"Nowhere Fast","artist":"Eminem","year":2017},
  {"title":"Offended","artist":"Eminem","year":2017},
  {"title":"Remind Me","artist":"Eminem","year":2017},
  {"title":"Remind Me (Intro)","artist":"Eminem","year":2017},
  {"title":"Revenge","artist":"P!nk","year":2017},
  {"title":"River","artist":"Eminem","year":2017},
  {"title":"Tragic Endings","artist":"Eminem","year":2017},
  {"title":"Untouchable","artist":"Eminem","year":2017},
  {"title":"Walk on Water","artist":"Eminem","year":2017},
  {"title":"Caterpillar","artist":"Royce da 5’9”","year":2018},
  {"title":"Fall","artist":"Eminem","year":2018},
  {"title":"Good Guy","artist":"Eminem","year":2018},
  {"title":"Greatest","artist":"Eminem","year":2018},
  {"title":"Kamikaze","artist":"Eminem","year":2018},
  {"title":"Killshot","artist":"Eminem","year":2018},
  {"title":"Lucky You","artist":"Eminem","year":2018},
  {"title":"Majesty","artist":"Nicki Minaj and Labrinth","year":2018},
  {"title":"Nice Guy","artist":"Eminem","year":2018},
  {"title":"Normal","artist":"Eminem","year":2018},
  {"title":"Not Alike","artist":"Eminem","year":2018},
  {"title":"Nowhere Fast (Extended Version)","artist":"Eminem","year":2018},
  {"title":"Stepping Stone","artist":"Eminem","year":2018},
  {"title":"The Ringer","artist":"Eminem","year":2018},
  {"title":"Venom (Music from the Motion Picture)","artist":"Eminem","year":2018},
  {"title":"Bang","artist":"Conway the Machine","year":2019},
  {"title":"Bang (Remix)","artist":"Griselda","year":2019},
  {"title":"Homicide","artist":"Logic","year":2019},
  {"title":"Lord Above","artist":"Fat Joe, Dre and Mary J. Blige","year":2019},
  {"title":"Rainy Days","artist":"Boogie","year":2019},
  {"title":"Remember the Name","artist":"Ed Sheeran","year":2019},
  {"title":"Alfred (Intro)","artist":"Eminem","year":2020},
  {"title":"Alfred (Outro)","artist":"Eminem","year":2020},
  {"title":"Alfred’s Theme","artist":"Eminem","year":2020},
  {"title":"Black Magic","artist":"Eminem","year":2020},
  {"title":"Book of Rhymes","artist":"Eminem","year":2020},
  {"title":"Coffin","artist":"Jessie Reyez","year":2020},
  {"title":"Darkness","artist":"Eminem","year":2020},
  {"title":"Discombobulated","artist":"Eminem","year":2020},
  {"title":"Farewell","artist":"Eminem","year":2020},
  {"title":"Favorite Bitch","artist":"Eminem","year":2020},
  {"title":"Friday Night Cypher","artist":"Big Sean","year":2020},
  {"title":"Gnat","artist":"Eminem","year":2020},
  {"title":"Godzilla","artist":"Eminem","year":2020},
  {"title":"Guns Blazing","artist":"Eminem","year":2020},
  {"title":"Higher","artist":"Eminem","year":2020},
  {"title":"In Too Deep","artist":"Eminem","year":2020},
  {"title":"I Will","artist":"Eminem","year":2020},
  {"title":"Killer","artist":"Eminem","year":2020},
  {"title":"Leaving Heaven","artist":"Eminem","year":2020},
  {"title":"Little Engine","artist":"Eminem","year":2020},
  {"title":"Lock It Up","artist":"Eminem","year":2020},
  {"title":"Marsh","artist":"Eminem","year":2020},
  {"title":"Never Love Again","artist":"Eminem","year":2020},
  {"title":"No Regrets","artist":"Eminem","year":2020},
  {"title":"Premonition (Intro)","artist":"Eminem","year":2020},
  {"title":"She Loves Me","artist":"Eminem","year":2020},
  {"title":"Stepdad","artist":"Eminem","year":2020},
  {"title":"Stepdad (Intro)","artist":"Eminem","year":2020},
  {"title":"The Adventures of Moon Man & Slim Shady","artist":"Kid Cudi","year":2020},
  {"title":"These Demons","artist":"Eminem","year":2020},
  {"title":"Those Kinda Nights","artist":"Eminem","year":2020},
  {"title":"Tone Deaf","artist":"Eminem","year":2020},
  {"title":"Unaccommodating","artist":"Eminem","year":2020},
  {"title":"Yah Yah","artist":"Eminem","year":2020},
  {"title":"You Gon’ Learn","artist":"Eminem","year":2020},
  {"title":"Zeus","artist":"Eminem","year":2020},
  {"title":"Eminem Speaks","artist":"Juice WRLD","year":2021},
  {"title":"EPMD 2","artist":"Nas and EPMD","year":2021},
  {"title":"Killer (Remix)","artist":"Eminem","year":2021},
  {"title":"Last One Standing","artist":"Skylar Grey","year":2021},
  {"title":"Walkthrough!","artist":"GRIP","year":2021},
  {"title":"From the D 2 the LBC","artist":"Eminem","year":2022},
  {"title":"Gospel","artist":"Dr. Dre","year":2022},
  {"title":"Is This Love (’09)","artist":"Eminem","year":2022},
  {"title":"Parables (Remix)","artist":"Cordae","year":2022},
  {"title":"The King and I","artist":"Eminem","year":2022},
  {"title":"Use This Gospel (Remix)","artist":"DJ Khaled","year":2022},
  {"title":"Lace It","artist":"Juice WRLD and Benny Blanco","year":2023},
  {"title":"Realest","artist":"Ez Mil","year":2023},
  {"title":"Antichrist","artist":"Eminem","year":2024},
  {"title":"Bad One","artist":"Eminem","year":2024},
  {"title":"Brand New Dance","artist":"Eminem","year":2024},
  {"title":"Doomsday Pt. 2","artist":"Eminem","year":2024},
  {"title":"Evil","artist":"Eminem","year":2024},
  {"title":"Fuel","artist":"Eminem","year":2024},
  {"title":"Fuel (Shady Edition)","artist":"Eminem","year":2024},
  {"title":"Guilty Conscience 2","artist":"Eminem","year":2024},
  {"title":"Gunz N Smoke","artist":"Snoop Dogg and Dr. Dre","year":2024},
  {"title":"Habits","artist":"Eminem","year":2024},
  {"title":"Head Honcho","artist":"Eminem","year":2024},
  {"title":"Houdini","artist":"Eminem","year":2024},
  {"title":"Kyrie & Luka","artist":"Eminem","year":2024},
];

const EMINEM_RELEASED_6 = [
  {"title":"Like My Shit","artist":"Eminem","year":2024},
  {"title":"Lucifer","artist":"Eminem","year":2024},
  {"title":"Murdergram Deux","artist":"LL Cool J","year":2024},
  {"title":"Renaissance","artist":"Eminem","year":2024},
  {"title":"Road Rage","artist":"Eminem","year":2024},
  {"title":"Somebody Save Me","artist":"Eminem","year":2024},
  {"title":"Temporary","artist":"Eminem","year":2024},
  {"title":"Tobey","artist":"Eminem","year":2024},
  {"title":"Trouble","artist":"Eminem","year":2024},
  {"title":"Everybody’s Looking at Me","artist":"Eminem","year":2025},
  {"title":"Stan (feat. Elton John)","artist":"Eminem","year":2025},
  {"title":"Stan (Live at Wembley 2014)","artist":"Eminem","year":2025},
  {"title":"Animals (Pt. I)","artist":"JID","year":2025},
  {"title":"Hello Operator / 'Till I Collapse (Live)","artist":"Eminem","year":2025},
];

const EMINEM_ARCHIVE_1 = [
  {"title":"Blown Away","artist":"Eminem","year":1988,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Eat It","artist":"Eminem","year":1988,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Foolish Pride","artist":"Eminem","year":1988,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Hard Motherfucker","artist":"Eminem","year":1988,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Pooh Butt Day (M&M and Chaos Kid version)","artist":"Eminem","year":1988,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Take 87 & A Half","artist":"Eminem","year":1988,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Teachin’ You a Lesson","artist":"Eminem","year":1988,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"As the Doom Surrounds with Gloom","artist":"Eminem","year":1989,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Purple Pimp Saga Bellbottom Pants","artist":"Eminem","year":1989,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"The First Suckerin Rhyme Ever","artist":"Eminem","year":1989,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Don’t Chew with Your Mouth Full","artist":"Eminem","year":1990,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Fattest Skinny Kid Alive","artist":"Eminem","year":1990,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Hammer vs. Vanilla","artist":"Eminem","year":1990,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Steppin' Onto the Scene","artist":"Eminem","year":1990,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Under New Management (Snippet)","artist":"Eminem","year":1990,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Artificial Flavour","artist":"Eminem","year":1991,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Bassmint Productions Freestyle","artist":"Eminem","year":1991,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Pooh Butt Day (Soul Intent version)","artist":"Eminem","year":1991,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Closer Than This (Live)","artist":"Eminem","year":1992,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"One-Handed Juggler","artist":"Eminem","year":1992,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Soul Intent","artist":"Eminem","year":1992,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Unrealistically Graphic","artist":"Eminem","year":1992,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"What Color Is Soul","artist":"Eminem","year":1992,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"So Many Styles (Snippet)","artist":"Eminem","year":1993,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"’94 Shit (Snippet)","artist":"Eminem","year":1994,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Wicked Shit (Snippet)","artist":"Eminem","year":1994,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Biterphobia","artist":"Eminem","year":1995,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Fuckin' Backstabber","artist":"Eminem","year":1995,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Mad Cold Blunts Is in the House","artist":"Eminem","year":1995,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Hip-Hop Shop Freestyle Battle","artist":"Eminem","year":1996,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Bad Meets Evil (Original)","artist":"Eminem","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Baruch College Radio Freestyle Tape","artist":"Eminem","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Bring Our Boys","artist":"D12","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Chance to Advance","artist":"D12","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Cum on Everybody (Original)","artist":"Eminem","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"DJ Yooter / Sway and Tech Freestyle","artist":"Eminem","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Filthy","artist":"D12","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"I’m Shady (Original)","artist":"Eminem","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rap Olympics ’97","artist":"Eminem","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rock Bottom (Original)","artist":"Eminem","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Scribble Jam ’97","artist":"Eminem","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Wake Up Show Freestyle — Greg","artist":"Eminem","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Wake Up Show Freestyle — It’s Only Fair to Warn","artist":"Eminem","year":1997,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Demon Inside","artist":"Eminem","year":1998,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Halftime Show Freestyle","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Hard Act to Follow","artist":"Eminem","year":1998,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"I’m Eminem (Freestyle)","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Kim (Original)","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"No One’s Iller (Demo Version)","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Stretch Armstrong & Bobbito Show Freestyle","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Wake Up Show Freestyle 1 (Gun in Your Grill)","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Wake Up Show Freestyle 2","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Wake Up Show Freestyle 3","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Wake Up Show Freestyle 4","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Wake Up Show Freestyle 5","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Wake Up Show Freestyle 6 (Chauvinist Pig)","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"When to Stand Up","artist":"Eminem","year":1998,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Where My Words At","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"XL Show Freestyle","artist":"Eminem","year":1998,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"4 Versus (Freestyle)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"88HipHop Freestyle","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Any Word (Freestyle)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Dissin’ Brandy and Mase (Freestyle)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Farm Club Freestyle","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"First Word (Freestyle)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Food Stamp (Freestyle)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Freestyle with Biggie","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Frontpage Stardom","artist":"Eminem","year":1999,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Getoe TV Freestyle","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"I Do Pop Pills (Freestyle)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"I’m Cancerous (Freestyle)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Kool Kid (Freestyle)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Macosa","artist":"Eminem","year":1999,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Mancow Freestyle","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"My Name Is (Original)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Mystikal Diss (Freestyle)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Pick It Up (Freestyle)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Renegade (Original with Royce da 5’9”)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Renewing the Staff (Freestyle)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Role Model Freestyle","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Role Model (Original)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Slim’s Freestyle","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Stereo Car Freestyle","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Sway & King Tech Freestyle","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"The Kids (Original)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Three Verses","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Turn Me Loose","artist":"Eminem","year":1999,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Watch Dees","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Weed Lacer (Freestyle)","artist":"Eminem","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"40 Minute Tim Westwood Freestyle","artist":"Eminem","year":2000,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Cocoa Brovas Freestyle","artist":"Eminem","year":2000,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"D12 Rap City Freestyle (2000)","artist":"Eminem","year":2000,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Freestyle Power 92.3","artist":"Eminem","year":2000,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Get Back","artist":"Tony Touch","year":2000,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"It’s Murder","artist":"Eminem","year":2000,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Just Rhymin’ (Freestyle)","artist":"Eminem","year":2000,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Off the Dome (Freestyle)","artist":"Eminem","year":2000,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"She’s the One","artist":"Bad Meets Evil","year":2000,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Things Ain’t the Same (Freestyle)","artist":"Eminem","year":2000,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Tylenol Island (Freestyle)","artist":"Eminem","year":2000,"catalogStatus":"archive","previewUnavailable":true},
];

const EMINEM_ARCHIVE_2 = [
  {"title":"We Takin’ Over This Year (Freestyle)","artist":"Eminem","year":2000,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Basket Case (Freestyle)","artist":"Eminem","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"D12 Rap City Freestyle (2001)","artist":"Eminem","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"D12 Tim Westwood Freestyle","artist":"Eminem","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Funk Flex Freestyle (2001)","artist":"Eminem","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Get Buzzed Intro","artist":"Eminem","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Still Number 1 (Freestyle)","artist":"Eminem","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Whether or Not","artist":"D12","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Confusion vs. Eminem","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"D12 Rap City Freestyle (Eminem’s Basement)","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Kay Slay Freestyle","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Marvwon vs. Eminem — Part 1","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Marvwon vs. Eminem — Part 2","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Maurice Grant vs. Eminem","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Nail in the Coffin","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rabbit & Cheddar Bob Freestyle","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rabbit Freestyle","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rabbit & Sol George Freestyle","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rabbit vs. Lickity Split","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rabbit vs. Lotto","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rabbit vs. Papa Doc","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rap City Freestyle","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Supa MC vs. Eminem","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Sweet Home Alabama (8 Mile performance)","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"The Invasion (Part One)","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"The Sauce","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Whoo Kid Freestyle","artist":"Eminem","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Bully","artist":"Eminem","year":2003,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Bump Heads","artist":"Eminem","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Can-I-Bitch","artist":"Eminem","year":2003,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Doe Rae Me (Hailie’s Revenge)","artist":"Eminem","year":2003,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Drunk Freestyle","artist":"Eminem","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Hail Mary","artist":"Eminem","year":2003,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Monkey See Monkey Do","artist":"Eminem","year":2003,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Phone Call from The E True Hollywood Mixtape","artist":"Eminem","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Wanksta (Eminem version)","artist":"Eminem","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Armageddon (The Invasion Part 3)","artist":"Eminem","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Canopy Freestyle","artist":"Eminem","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Got It Twisted (Tim Westwood Freestyle)","artist":"Eminem","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Hardest Motherfuckers (Freestyle)","artist":"Eminem","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"I Like a Girl (Freestyle)","artist":"Eminem","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Radio 1 Shady Camp Freestyle","artist":"Eminem","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rap Battle with Sway","artist":"Eminem","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rock N Roll Freestyle","artist":"Eminem","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Shade 45 Freestyle","artist":"Eminem","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Shady Camp Tim Westwood Freestyle","artist":"Eminem","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Anger Management","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Freestyle (“I Got a Riddle…”)","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Freestyle (The Way I Am DVD)","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Fubba U Cubba Cubba","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Fuck Whoo Kid","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Get Off My Nuts (Freestyle)","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"I’ll Hurt You","artist":"Busta Rhymes","year":2005,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Live on Shade 45","artist":"50 Cent and Charlie Murphy","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Live on Shade 45 Outro","artist":"50 Cent and Charlie Murphy","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"My Ballz","artist":"D12","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Pimplikeness","artist":"Proof","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Sada Pop","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Speechtone 1 — Answer Your Phone Before Your Mother Gets Mad at Me","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Speechtone 2 — Answer Your Phone, Son of a Bitch","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Speechtone 3 — Before I Get More Annoying","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Speechtone 4 — Get Your Fucking Hand Off Your Cock","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Speechtone 5 — I Don’t Care If Your Breath Smells Like Shit","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Speechtone 6 — It’s Slim Shady… Answer Your Phone","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Speechtone 7 — Press Talk, Dummy","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Speechtone 8 — Pubic Hairs Roasting on an Open Fire","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Speechtone 9 — Ring Ring Ring, Slim Shady","artist":"Eminem","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Classic Beatbox Freestyle","artist":"Eminem","year":2006,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Difficult","artist":"Eminem","year":2006,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Smashtime Radio Intro","artist":"Eminem","year":2006,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Smashtime Radio Outro","artist":"Eminem","year":2006,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"The Pre-Up Introduction","artist":"Eminem","year":2006,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"You Hear Me Pt. 2","artist":"Eminem","year":2006,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Touch It (Remix — Live at the 2006 BET Awards)","artist":"Busta Rhymes","year":2006,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"50 Ways","artist":"Eminem","year":2007,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Keys to the City","artist":"Eminem","year":2007,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Shady Baby","artist":"Obie Trice","year":2007,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Step Right Up (Freestyle)","artist":"Eminem","year":2007,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Syllables","artist":"Eminem","year":2007,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"The Apple","artist":"Eminem","year":2007,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Shade 45 Commercial (2008)","artist":"Eminem","year":2008,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Stan (The Lost Verses — Shade 45)","artist":"Eminem","year":2008,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"I’m Having a Relapse","artist":"Eminem","year":2008,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"BET Cypher 2009","artist":"Eminem","year":2009,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Chonkyfire (Freestyle)","artist":"Eminem","year":2009,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"I Just Relapsed","artist":"Eminem","year":2009,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Microphone (Freestyle)","artist":"Eminem","year":2009,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rap City Relapse Freestyle","artist":"Eminem","year":2009,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Respect My Conglomerate (Freestyle)","artist":"Eminem","year":2009,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rock the Bells (Live)","artist":"Eminem","year":2009,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"The Warning","artist":"Eminem","year":2009,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Tim Westwood Freestyle","artist":"Eminem","year":2009,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Zucker im Kaffee (Freestyle)","artist":"Eminem","year":2009,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Ballin’ Uncontrollably","artist":"Eminem","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Celebrity (Eminem Version)","artist":"Lloyd Banks","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Cocaine","artist":"Eminem","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Despicable (Freestyle)","artist":"Eminem","year":2010,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Everything","artist":"Eminem","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Fly Away","artist":"Eminem","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Going Crazy","artist":"Eminem","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
];

const EMINEM_ARCHIVE_3 = [
  {"title":"Hello, Good Morning (Eminem Remix)","artist":"Diddy–Dirty Money","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Tim Westwood Freestyle (2010)","artist":"Eminem","year":2010,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Topless","artist":"Dr. Dre","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"2.0 Boys","artist":"Eminem","year":2011,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"BET Cypher 2011","artist":"Eminem","year":2011,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"D12 Eminem Intro","artist":"D12","year":2011,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Die Hard (Snippet)","artist":"Dr. Dre","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Dudey","artist":"Eminem","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Fame","artist":"D12","year":2011,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Fame (Original — Going Crazy)","artist":"D12","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Get Money","artist":"Eminem","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Give Me the Ball","artist":"Eminem","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"G.O.A.T.","artist":"Eminem","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Hit Me with Your Best Shot","artist":"Eminem","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"It’s Been Real","artist":"Eminem","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Murder One","artist":"50 Cent","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Oh No","artist":"Eminem","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Talk to Me","artist":"Young Jeezy","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Wee Wee","artist":"Eminem","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Art of Rap Freestyle","artist":"Eminem","year":2012,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Rap City EM360 Freestyle","artist":"Eminem","year":2013,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Road to Total Slaughter Freestyle","artist":"Eminem","year":2014,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"SHADY CXVPHER","artist":"Eminem","year":2014,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Shady XV Outro","artist":"Eminem","year":2014,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Shady XV Shoutout","artist":"Eminem","year":2014,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Vancouver Freestyle","artist":"Eminem","year":2014,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Sway in the Morning Freestyle","artist":"Eminem","year":2015,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"The Storm","artist":"Eminem","year":2017,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Kick Off (Freestyle)","artist":"Eminem","year":2018,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Nut Up","artist":"Eminem","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Welcome to Shady Con","artist":"Eminem","year":2021,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Mind Blowin’","artist":"Eminem","year":2022,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Antichrist ’05","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Back and Forth (Discombobulated OG)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Careful What You Wish For (Long Version)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Christopher Reeves (OG)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Follow Me","artist":"Nate Dogg","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Freak","artist":"Westside Boogie and Anderson .Paak","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"I’m Sorry","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"I’m Twisted (Freestyle)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Jump Out","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Key to My Room","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Little Engine (Alternate Version)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Love Drunk","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Marshall Powers","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"My 1st Single (Demo)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"My Darling (Long Version)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"No Regrets (Demo)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Renaissance (Demo)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Ritz","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Sexual Healing (Dr. Dre Reference)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Sexual Healing (Is This Love — Original)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Smack You","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Sociopath","artist":"50 Cent","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Stepping Stone (OG/Demo)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Take It","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"This Is (Survival OG)","artist":"Eminem","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Trade Off","artist":"Slaughterhouse","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
];

export const EMINEM_SONGS = [
  ...EMINEM_RELEASED_1,
  ...EMINEM_RELEASED_2,
  ...EMINEM_RELEASED_3,
  ...EMINEM_RELEASED_4,
  ...EMINEM_RELEASED_5,
  ...EMINEM_RELEASED_6,
  ...EMINEM_ARCHIVE_1,
  ...EMINEM_ARCHIVE_2,
  ...EMINEM_ARCHIVE_3,
];
