// Name That Tune: Kanye West catalogue snapshot (reviewed 2026-08-03).
// Sources: Wikipedia's Kanye West discography, singles discography and
// "List of songs recorded by Kanye West"; the Kanye West Wiki's unreleased-song
// categories and project pages; Internet Archive copies of the Freshmen
// Adjustment and Go-Getters tapes; leak-tracker mirrors cross-checked against
// Complex/Pitchfork/HipHopDX reporting.
//
// Released tracks are songs Kanye performs on, whether he leads or guests;
// songs he only produced are not here. The exception is a project he authored:
// Cruel Summer and Jesus Is Born are carried whole, so a few of their tracks
// have no Kanye vocal. Spoken skits with no musical performance are excluded.
// Archive and unreleased records stay catalogued but are flagged
// previewUnavailable, because Deezer and iTunes have no authorised preview to
// sell — they never enter a game pool.
//
// Only released songs are deduplicated on title alone, because only they can be
// drawn and two cards must never share a tune: a guest credit that later landed
// on an album collapses to its first release. Six same-title pairs survive that
// rule as reviewed exceptions — different songs that happen to share a name.
// Archive and unreleased entries collapse only against the same title by the
// same artist, so a leak named after a released cut is kept.

const KANYE_RELEASED_1 = [
  {"title":"Line for Line","artist":"Grav","year":1996},
  {"title":"Is It You? (Deja Vu) (Remix)","artist":"Made Men","year":1999},
  {"title":"What You Do to Me","artist":"Infamous Syndicate","year":1999},
  {"title":"Let's Get Married (Reception Remix)","artist":"Jagged Edge","year":2000},
  {"title":"Never Change","artist":"Jay-Z","year":2001},
  {"title":"Welcome 2 Chicago","artist":"Abstract Mindstate","year":2001},
  {"title":"Champions","artist":"Dame Dash","year":2002},
  {"title":"Guerilla Monsoon Rap","artist":"Talib Kweli","year":2002},
  {"title":"Guess Who's Back","artist":"Scarface","year":2002},
  {"title":"The Bounce","artist":"Jay-Z","year":2002},
  {"title":"Changing Lanes","artist":"Chops","year":2003},
  {"title":"Get By (Remix)","artist":"Talib Kweli","year":2003},
  {"title":"Hold On (Remix)","artist":"Dwele","year":2003},
  {"title":"Slow Jamz","artist":"Twista","year":2003},
  {"title":"All Falls Down","artist":"Kanye West","year":2004},
  {"title":"Breathe In Breathe Out","artist":"Kanye West","year":2004},
  {"title":"Candy","artist":"Myleka","year":2004},
  {"title":"Confessions Part II (Remix)","artist":"Usher","year":2004},
  {"title":"Down and Out","artist":"Cam'ron","year":2004},
  {"title":"Family Business","artist":"Kanye West","year":2004},
  {"title":"Get Em High","artist":"Kanye West","year":2004},
  {"title":"Gettin' It In","artist":"Jadakiss","year":2004},
  {"title":"Graduation Day","artist":"Kanye West","year":2004},
  {"title":"Higher","artist":"Do or Die","year":2004},
  {"title":"I Got a Love","artist":"Jin","year":2004},
  {"title":"I'll Fly Away","artist":"Kanye West","year":2004},
  {"title":"Jesus Walks","artist":"Kanye West","year":2004},
  {"title":"Last Call","artist":"Kanye West","year":2004},
  {"title":"My Baby","artist":"Janet Jackson","year":2004},
  {"title":"Never Let Me Down","artist":"Kanye West","year":2004},
  {"title":"Oh Oh","artist":"Melbeatz","year":2004},
  {"title":"Overnight Celebrity","artist":"Twista","year":2004},
  {"title":"Real Love","artist":"Rell","year":2004},
  {"title":"School Spirit","artist":"Kanye West","year":2004},
  {"title":"Selfish","artist":"Slum Village","year":2004},
  {"title":"Spaceship","artist":"Kanye West","year":2004},
  {"title":"Talk About Our Love","artist":"Brandy","year":2004},
  {"title":"The New Workout Plan","artist":"Kanye West","year":2004},
  {"title":"The Way That You Do","artist":"Carl Thomas","year":2004},
  {"title":"This Way","artist":"Dilated Peoples","year":2004},
  {"title":"Through the Wire","artist":"Kanye West","year":2004},
  {"title":"Two Words","artist":"Kanye West","year":2004},
  {"title":"U Know","artist":"White Boy","year":2004},
  {"title":"We Don't Care","artist":"Kanye West","year":2004},
  {"title":"Addiction","artist":"Kanye West","year":2005},
  {"title":"Back to Basics","artist":"Kanye West","year":2005},
  {"title":"Brand New","artist":"Rhymefest","year":2005},
  {"title":"Bring Me Down","artist":"Kanye West","year":2005},
  {"title":"Celebration","artist":"Kanye West","year":2005},
  {"title":"Crack Music","artist":"Kanye West","year":2005},
  {"title":"Diamonds from Sierra Leone","artist":"Kanye West","year":2005},
  {"title":"Diamonds from Sierra Leone (Remix)","artist":"Kanye West","year":2005},
  {"title":"Drive Slow","artist":"Kanye West","year":2005},
  {"title":"Extravaganza","artist":"Jamie Foxx","year":2005},
  {"title":"Fly Away","artist":"Miri Ben-Ari","year":2005},
  {"title":"Go!","artist":"Common","year":2005},
  {"title":"Gold Digger","artist":"Kanye West","year":2005},
  {"title":"Gone","artist":"Kanye West","year":2005},
  {"title":"Grown Man, Pt. 2","artist":"Young Gunz","year":2005},
  {"title":"Heard 'Em Say","artist":"Kanye West","year":2005},
  {"title":"Heavy Hitters","artist":"Kanye West","year":2005},
  {"title":"Hey Mama","artist":"Kanye West","year":2005},
  {"title":"It's Alright (Welcome Back Remix)","artist":"Kanye West","year":2005},
  {"title":"Late","artist":"Kanye West","year":2005},
  {"title":"My Way Home","artist":"Kanye West","year":2005},
  {"title":"Number One","artist":"John Legend","year":2005},
  {"title":"Paid the Price","artist":"Do or Die","year":2005},
  {"title":"Pusha Man","artist":"Bump J","year":2005},
  {"title":"Roses","artist":"Kanye West","year":2005},
  {"title":"Side 2 Side (Extended Remix)","artist":"Three 6 Mafia","year":2005},
  {"title":"The Corner","artist":"Common","year":2005},
  {"title":"The Food","artist":"Common","year":2005},
  {"title":"The New Workout Plan (Remix)","artist":"Kanye West","year":2005},
  {"title":"They Say","artist":"Common","year":2005},
  {"title":"Touch the Sky","artist":"Kanye West","year":2005},
  {"title":"We Can Make It Better","artist":"Kanye West","year":2005},
  {"title":"We Major","artist":"Kanye West","year":2005},
  {"title":"Wouldn't You Like to Ride?","artist":"Malik Yusef","year":2005},
  {"title":"Anything","artist":"Patti LaBelle","year":2006},
  {"title":"Back Like That (Remix)","artist":"Ghostface Killah","year":2006},
  {"title":"Ghetto","artist":"Smitty","year":2006},
  {"title":"Grammy Family","artist":"DJ Khaled","year":2006},
  {"title":"Impossible","artist":"Kanye West","year":2006},
  {"title":"Like This","artist":"DJ Clue?","year":2006},
  {"title":"More","artist":"Rhymefest","year":2006},
  {"title":"Still Dreaming","artist":"Nas","year":2006},
  {"title":"Tell Me When to Go (Remix)","artist":"E-40","year":2006},
  {"title":"Wouldn't Get Far","artist":"The Game","year":2006},
  {"title":"Barry Bonds","artist":"Kanye West","year":2007},
  {"title":"Because of You (Remix)","artist":"Ne-Yo","year":2007},
  {"title":"Big Brother","artist":"Kanye West","year":2007},
  {"title":"Bittersweet Poetry","artist":"Kanye West","year":2007},
  {"title":"Buy U a Drank (Shawty Snappin') (Remix)","artist":"T-Pain","year":2007},
  {"title":"Can't Tell Me Nothing","artist":"Kanye West","year":2007},
  {"title":"Champion","artist":"Kanye West","year":2007},
  {"title":"Classic (Better Than I've Ever Been)","artist":"Kanye West","year":2007},
  {"title":"Down","artist":"Chris Brown","year":2007},
  {"title":"Drunk and Hot Girls","artist":"Kanye West","year":2007},
  {"title":"Everything I Am","artist":"Kanye West","year":2007},
  {"title":"Flashing Lights","artist":"Kanye West","year":2007},
];

const KANYE_RELEASED_2 = [
  {"title":"Good Life","artist":"Kanye West","year":2007},
  {"title":"Good Morning","artist":"Kanye West","year":2007},
  {"title":"Good Night","artist":"Kanye West","year":2007},
  {"title":"Homecoming","artist":"Kanye West","year":2007},
  {"title":"I Still Love H.E.R.","artist":"Teriyaki Boyz","year":2007},
  {"title":"I Wonder","artist":"Kanye West","year":2007},
  {"title":"I'ma Get You","artist":"N.O.R.E.","year":2007},
  {"title":"In the Mood","artist":"Talib Kweli","year":2007},
  {"title":"My Drink n My 2 Step (Remix)","artist":"Cassidy","year":2007},
  {"title":"No One (Curtis Lynch Reggae Mix)","artist":"Alicia Keys","year":2007},
  {"title":"Pro Nails","artist":"Kid Sister","year":2007},
  {"title":"Southside","artist":"Common","year":2007},
  {"title":"Stronger","artist":"Kanye West","year":2007},
  {"title":"The Glory","artist":"Kanye West","year":2007},
  {"title":"The Good, the Bad, the Ugly","artist":"Consequence","year":2007},
  {"title":"This Ain't a Scene, It's an Arms Race (Remix)","artist":"Fall Out Boy","year":2007},
  {"title":"Amazing","artist":"Kanye West","year":2008},
  {"title":"American Boy","artist":"Estelle","year":2008},
  {"title":"Bad News","artist":"Kanye West","year":2008},
  {"title":"Beat Goes On","artist":"Madonna","year":2008},
  {"title":"Billie Jean 2008","artist":"Michael Jackson","year":2008},
  {"title":"Coldest Winter","artist":"Kanye West","year":2008},
  {"title":"Everybody","artist":"Fonzworth Bentley","year":2008},
  {"title":"Everyone Nose (All the Girls Standing in the Line for the Bathroom) (Remix)","artist":"N.E.R.D","year":2008},
  {"title":"Finer Things","artist":"DJ Felli Fel","year":2008},
  {"title":"Go Hard","artist":"DJ Khaled","year":2008},
  {"title":"Heartless","artist":"Kanye West","year":2008},
  {"title":"It's Over","artist":"John Legend","year":2008},
  {"title":"Lollipop (Remix)","artist":"Lil Wayne","year":2008},
  {"title":"Love Lockdown","artist":"Kanye West","year":2008},
  {"title":"Paranoid","artist":"Kanye West","year":2008},
  {"title":"Pinocchio Story","artist":"Kanye West","year":2008},
  {"title":"Plastic","artist":"Really Doe","year":2008},
  {"title":"Promised Land","artist":"Malik Yusef","year":2008},
  {"title":"Punch Drunk Love (The Eye)","artist":"Common","year":2008},
  {"title":"Purrty Woman","artist":"Kidz in the Hall","year":2008},
  {"title":"Put On","artist":"Young Jeezy","year":2008},
  {"title":"RoboCop","artist":"Kanye West","year":2008},
  {"title":"Say You Will","artist":"Kanye West","year":2008},
  {"title":"See You in My Nightmares","artist":"Kanye West","year":2008},
  {"title":"Stay Up! (Viagra)","artist":"88-Keys","year":2008},
  {"title":"Street Lights","artist":"Kanye West","year":2008},
  {"title":"Swagga Like Us","artist":"T.I. & Jay-Z","year":2008},
  {"title":"Therapy","artist":"T-Pain","year":2008},
  {"title":"Welcome to Heartbreak","artist":"Kanye West","year":2008},
  {"title":"Alors on Danse (Remix)","artist":"Stromae","year":2009},
  {"title":"Alright","artist":"Twista","year":2009},
  {"title":"Anyone but Him","artist":"Mr Hudson","year":2009},
  {"title":"Ayyy Girl","artist":"JYJ","year":2009},
  {"title":"Digital Girl (Remix)","artist":"Jamie Foxx","year":2009},
  {"title":"Ego (Remix)","artist":"Beyonce","year":2009},
  {"title":"Flight School","artist":"GLC","year":2009},
  {"title":"Forever","artist":"Drake","year":2009},
  {"title":"Gifted","artist":"N.A.S.A.","year":2009},
  {"title":"Hate","artist":"Jay-Z","year":2009},
  {"title":"In for the Kill (Remix)","artist":"La Roux","year":2009},
  {"title":"Kinda Like a Big Deal","artist":"Clipse","year":2009},
  {"title":"Knock You Down","artist":"Keri Hilson","year":2009},
  {"title":"Magic Man","artist":"Malik Yusef","year":2009},
  {"title":"Make Her Say","artist":"Kid Cudi","year":2009},
  {"title":"Maybach Music 2","artist":"Rick Ross","year":2009},
  {"title":"Run This Town","artist":"Jay-Z","year":2009},
  {"title":"Supernova","artist":"Mr Hudson","year":2009},
  {"title":"Teriyaking","artist":"Teriyaki Boyz","year":2009},
  {"title":"The Big Screen","artist":"GLC","year":2009},
  {"title":"Walkin' on the Moon","artist":"The-Dream","year":2009},
  {"title":"We Fight/We Love (Remix)","artist":"Consequence","year":2009},
  {"title":"Whatever U Want","artist":"Consequence","year":2009},
  {"title":"All of the Lights","artist":"Kanye West","year":2010},
  {"title":"All of the Lights (Interlude)","artist":"Kanye West","year":2010},
  {"title":"Blame Game","artist":"Kanye West","year":2010},
  {"title":"Blazin'","artist":"Nicki Minaj","year":2010},
  {"title":"Chain Heavy","artist":"Kanye West","year":2010},
  {"title":"Christian Dior Denim Flow","artist":"Kanye West","year":2010},
  {"title":"Christmas in Harlem","artist":"Kanye West","year":2010},
  {"title":"Dark Fantasy","artist":"Kanye West","year":2010},
  {"title":"Deuces (Remix)","artist":"Chris Brown","year":2010},
  {"title":"Devil in a New Dress","artist":"Kanye West","year":2010},
  {"title":"Don't Look Down","artist":"Kanye West","year":2010},
  {"title":"Erase Me","artist":"Kid Cudi","year":2010},
  {"title":"Good Friday","artist":"Kanye West","year":2010},
  {"title":"Gorgeous","artist":"Kanye West","year":2010},
  {"title":"Hell of a Life","artist":"Kanye West","year":2010},
  {"title":"Hurricane 2.0","artist":"Thirty Seconds to Mars","year":2010},
  {"title":"Live Fast, Die Young","artist":"Rick Ross","year":2010},
  {"title":"Looking for Trouble","artist":"Kanye West","year":2010},
  {"title":"Lord Lord Lord","artist":"Kanye West","year":2010},
  {"title":"Lost in the World","artist":"Kanye West","year":2010},
  {"title":"Monster","artist":"Kanye West","year":2010},
  {"title":"Power","artist":"Kanye West","year":2010},
  {"title":"Power (Remix)","artist":"Kanye West","year":2010},
  {"title":"Pretty Girl Rock (Remix)","artist":"Keri Hilson","year":2010},
  {"title":"Runaway","artist":"Kanye West","year":2010},
  {"title":"Runaway Love (Remix)","artist":"Justin Bieber","year":2010},
  {"title":"See Me Now","artist":"Kanye West","year":2010},
  {"title":"So Appalled","artist":"Kanye West","year":2010},
  {"title":"Start It Up","artist":"Lloyd Banks","year":2010},
  {"title":"Take One for the Team","artist":"Kanye West","year":2010},
  {"title":"We Are the World 25 for Haiti","artist":"Artists for Haiti","year":2010},
  {"title":"Welcome to the World","artist":"T.I.","year":2010},
];

const KANYE_RELEASED_3 = [
  {"title":"Who Will Survive in America","artist":"Kanye West","year":2010},
  {"title":"Amen","artist":"Pusha T","year":2011},
  {"title":"E.T.","artist":"Katy Perry","year":2011},
  {"title":"Eyez Closed","artist":"Snoop Dogg","year":2011},
  {"title":"Gotta Have It","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"H.A.M.","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"Illest Motherfucker Alive","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"Lift Off","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"Made in America","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"Marvin & Chardonnay","artist":"Big Sean","year":2011},
  {"title":"Murder to Excellence","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"New Day","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"Niggas in Paris","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"No Church in the Wild","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"Otis","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"Primetime","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"Sailing NOT Selling","artist":"Jhene Aiko","year":2011},
  {"title":"That's My Bitch","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"The Joy","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"Touch It","artist":"Pusha T","year":2011},
  {"title":"Welcome to the Jungle","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"Who Gon Stop Me","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"Why I Love You","artist":"Jay-Z & Kanye West","year":2011},
  {"title":"Another You","artist":"The World Famous Tony Williams","year":2012},
  {"title":"Birthday Song","artist":"2 Chainz","year":2012},
  {"title":"Bliss","artist":"GOOD Music","year":2012},
  {"title":"Clique","artist":"GOOD Music","year":2012},
  {"title":"Cold.1","artist":"GOOD Music","year":2012},
  {"title":"Creepers","artist":"GOOD Music","year":2012},
  {"title":"Diamonds (Remix)","artist":"Rihanna","year":2012},
  {"title":"Don't Like.1","artist":"GOOD Music","year":2012},
  {"title":"Higher","artist":"GOOD Music","year":2012},
  {"title":"I Wish You Would","artist":"DJ Khaled","year":2012},
  {"title":"Jesus Piece","artist":"The Game","year":2012},
  {"title":"Mercy.1","artist":"GOOD Music","year":2012},
  {"title":"New God Flow.1","artist":"GOOD Music","year":2012},
  {"title":"Pride N Joy","artist":"Fat Joe","year":2012},
  {"title":"Rollin'","artist":"The Game","year":2012},
  {"title":"Sin City","artist":"GOOD Music","year":2012},
  {"title":"The Morning","artist":"GOOD Music","year":2012},
  {"title":"The One","artist":"GOOD Music","year":2012},
  {"title":"To the World","artist":"GOOD Music","year":2012},
  {"title":"Way Too Cold (Theraflu)","artist":"Kanye West","year":2012},
  {"title":"White Dress","artist":"Kanye West","year":2012},
  {"title":"Black Skinhead","artist":"Kanye West","year":2013},
  {"title":"Blood on the Leaves","artist":"Kanye West","year":2013},
  {"title":"Bound 2","artist":"Kanye West","year":2013},
  {"title":"Guilt Trip","artist":"Kanye West","year":2013},
  {"title":"Hold My Liquor","artist":"Kanye West","year":2013},
  {"title":"I Am a God","artist":"Kanye West","year":2013},
  {"title":"I'm in It","artist":"Kanye West","year":2013},
  {"title":"New Slaves","artist":"Kanye West","year":2013},
  {"title":"On Sight","artist":"Kanye West","year":2013},
  {"title":"Scape Goat (The Fix)","artist":"D'banj","year":2013},
  {"title":"Send It Up","artist":"Kanye West","year":2013},
  {"title":"Thank You","artist":"Busta Rhymes","year":2013},
  {"title":"Can't Stop","artist":"Theophilus London","year":2014},
  {"title":"Drunk in Love (Remix)","artist":"Beyonce","year":2014},
  {"title":"I Won","artist":"Future","year":2014},
  {"title":"Nobody","artist":"Chief Keef","year":2014},
  {"title":"Only One","artist":"Kanye West","year":2014},
  {"title":"Sanctified","artist":"Rick Ross","year":2014},
  {"title":"All Day","artist":"Kanye West","year":2015},
  {"title":"All Your Fault","artist":"Big Sean","year":2015},
  {"title":"Blessings (Extended Version)","artist":"Big Sean","year":2015},
  {"title":"Facts","artist":"Kanye West","year":2015},
  {"title":"FourFiveSeconds","artist":"Rihanna","year":2015},
  {"title":"Guard Down","artist":"Ty Dolla $ign","year":2015},
  {"title":"Jukebox Joints","artist":"A$AP Rocky","year":2015},
  {"title":"M.P.A.","artist":"Pusha T","year":2015},
  {"title":"Mula","artist":"The Game","year":2015},
  {"title":"One Man Can Change the World","artist":"Big Sean","year":2015},
  {"title":"Piss on Your Grave","artist":"Travis Scott","year":2015},
  {"title":"Smuckers","artist":"Tyler, the Creator","year":2015},
  {"title":"The Summer League","artist":"Wale","year":2015},
  {"title":"U Mad","artist":"Vic Mensa","year":2015},
  {"title":"30 Hours","artist":"Kanye West","year":2016},
  {"title":"All We Got","artist":"Chance the Rapper","year":2016},
  {"title":"Ballin'","artist":"Juicy J","year":2016},
  {"title":"Castro","artist":"Yo Gotti","year":2016},
  {"title":"Champions (Round & Round)","artist":"GOOD Music","year":2016},
  {"title":"Facts (Charlie Heat Version)","artist":"Kanye West","year":2016},
  {"title":"Fade","artist":"Kanye West","year":2016},
  {"title":"Famous","artist":"Kanye West","year":2016},
  {"title":"Father Stretch My Hands Pt. 1","artist":"Kanye West","year":2016},
  {"title":"Feedback","artist":"Kanye West","year":2016},
  {"title":"Figure It Out","artist":"French Montana","year":2016},
  {"title":"FML","artist":"Kanye West","year":2016},
  {"title":"Frank's Track","artist":"Kanye West","year":2016},
  {"title":"Freestyle 4","artist":"Kanye West","year":2016},
  {"title":"Friends","artist":"Francis and the Lights","year":2016},
  {"title":"Highlights","artist":"Kanye West","year":2016},
  {"title":"I Love Kanye","artist":"Kanye West","year":2016},
  {"title":"In Common (Remix)","artist":"Alicia Keys","year":2016},
  {"title":"Low Lights","artist":"Kanye West","year":2016},
  {"title":"My City's Gone","artist":"Francis and the Lights","year":2016},
  {"title":"No More Parties in L.A.","artist":"Kanye West","year":2016},
  {"title":"Pop Style (Extended Version)","artist":"Drake","year":2016},
  {"title":"Pt. 2","artist":"Kanye West","year":2016},
  {"title":"Pussy Print","artist":"Gucci Mane","year":2016},
];

const KANYE_RELEASED_4 = [
  {"title":"Real Friends","artist":"Kanye West","year":2016},
  {"title":"Saint Pablo","artist":"Kanye West","year":2016},
  {"title":"That Part","artist":"ScHoolboy Q","year":2016},
  {"title":"The Killing Season","artist":"A Tribe Called Quest","year":2016},
  {"title":"Tiimmy Turner (Remix)","artist":"Desiigner","year":2016},
  {"title":"Ultralight Beam","artist":"Kanye West","year":2016},
  {"title":"Waves","artist":"Kanye West","year":2016},
  {"title":"Wolves","artist":"Kanye West","year":2016},
  {"title":"Dat Side","artist":"CyHi the Prynce","year":2017},
  {"title":"Feel Me","artist":"Tyga","year":2017},
  {"title":"Glow","artist":"Drake","year":2017},
  {"title":"Love Yourself","artist":"Mary J. Blige","year":2017},
  {"title":"4th Dimension","artist":"Kids See Ghosts","year":2018},
  {"title":"All Mine","artist":"Kanye West","year":2018},
  {"title":"Cops Shot the Kid","artist":"Nas","year":2018},
  {"title":"Cudi Montage","artist":"Kids See Ghosts","year":2018},
  {"title":"Everything","artist":"Nas","year":2018},
  {"title":"Feel the Love","artist":"Kids See Ghosts","year":2018},
  {"title":"Fire","artist":"Kids See Ghosts","year":2018},
  {"title":"Freeee (Ghost Town, Pt. 2)","artist":"Kids See Ghosts","year":2018},
  {"title":"Ghost Town","artist":"Kanye West","year":2018},
  {"title":"Hurry","artist":"Teyana Taylor","year":2018},
  {"title":"I Love It","artist":"Kanye West","year":2018},
  {"title":"I Thought About Killing You","artist":"Kanye West","year":2018},
  {"title":"Kanga","artist":"6ix9ine","year":2018},
  {"title":"Kids See Ghosts","artist":"Kids See Ghosts","year":2018},
  {"title":"Lift Yourself","artist":"Kanye West","year":2018},
  {"title":"Mama","artist":"6ix9ine","year":2018},
  {"title":"No Mistakes","artist":"Kanye West","year":2018},
  {"title":"One Minute","artist":"XXXTentacion","year":2018},
  {"title":"Reborn","artist":"Kids See Ghosts","year":2018},
  {"title":"Violent Crimes","artist":"Kanye West","year":2018},
  {"title":"Watch","artist":"Travis Scott","year":2018},
  {"title":"What Would Meek Do?","artist":"Pusha T","year":2018},
  {"title":"Wouldn't Leave","artist":"Kanye West","year":2018},
  {"title":"XTCY","artist":"Kanye West","year":2018},
  {"title":"Ye vs. the People","artist":"Kanye West","year":2018},
  {"title":"Yikes","artist":"Kanye West","year":2018},
  {"title":"Back to Life","artist":"Sunday Service Choir","year":2019},
  {"title":"Balm in Gilead","artist":"Sunday Service Choir","year":2019},
  {"title":"Closed on Sunday","artist":"Kanye West","year":2019},
  {"title":"Count Your Blessings","artist":"Sunday Service Choir","year":2019},
  {"title":"Every Hour","artist":"Kanye West","year":2019},
  {"title":"Everything We Need","artist":"Kanye West","year":2019},
  {"title":"Excellent","artist":"Sunday Service Choir","year":2019},
  {"title":"Father Stretch","artist":"Sunday Service Choir","year":2019},
  {"title":"Follow God","artist":"Kanye West","year":2019},
  {"title":"Follow Me - Faith","artist":"Sunday Service Choir","year":2019},
  {"title":"God Is","artist":"Kanye West","year":2019},
  {"title":"Hands On","artist":"Kanye West","year":2019},
  {"title":"Jesus Is Lord","artist":"Kanye West","year":2019},
  {"title":"Lift Up Your Voices","artist":"Sunday Service Choir","year":2019},
  {"title":"Mixed Personalities","artist":"YNW Melly","year":2019},
  {"title":"More Than Anything","artist":"Sunday Service Choir","year":2019},
  {"title":"On God","artist":"Kanye West","year":2019},
  {"title":"Paradise","artist":"Sunday Service Choir","year":2019},
  {"title":"Puppet","artist":"Tyler, the Creator","year":2019},
  {"title":"Rain","artist":"Sunday Service Choir","year":2019},
  {"title":"Revelations 19:1","artist":"Sunday Service Choir","year":2019},
  {"title":"Satan, We're Gonna Tear Your Kingdom Down","artist":"Sunday Service Choir","year":2019},
  {"title":"Selah","artist":"Kanye West","year":2019},
  {"title":"Souls Anchored","artist":"Sunday Service Choir","year":2019},
  {"title":"Sunshine","artist":"Sunday Service Choir","year":2019},
  {"title":"Sweet Grace","artist":"Sunday Service Choir","year":2019},
  {"title":"Take Me to the Light","artist":"Francis and the Lights","year":2019},
  {"title":"That's How the Good Lord Works","artist":"Sunday Service Choir","year":2019},
  {"title":"Total Praise","artist":"Sunday Service Choir","year":2019},
  {"title":"Ultralight Beam","artist":"Sunday Service Choir","year":2019},
  {"title":"Use This Gospel","artist":"Kanye West","year":2019},
  {"title":"Water","artist":"Kanye West","year":2019},
  {"title":"Weak","artist":"Sunday Service Choir","year":2019},
  {"title":"Ego Death","artist":"Ty Dolla $ign","year":2020},
  {"title":"Feel a Way","artist":"2 Chainz","year":2020},
  {"title":"Go2DaMoon","artist":"Playboi Carti","year":2020},
  {"title":"Nah Nah Nah","artist":"Kanye West","year":2020},
  {"title":"Nah Nah Nah (Remix)","artist":"Kanye West","year":2020},
  {"title":"Pray 4 Me","artist":"SAINt JHN","year":2020},
  {"title":"Smack DVD","artist":"SAINt JHN","year":2020},
  {"title":"Track 6","artist":"Ty Dolla $ign","year":2020},
  {"title":"Wash Us in the Blood","artist":"Kanye West","year":2020},
  {"title":"24","artist":"Kanye West","year":2021},
  {"title":"Believe What I Say","artist":"Kanye West","year":2021},
  {"title":"Come to Life","artist":"Kanye West","year":2021},
  {"title":"Donda","artist":"Kanye West","year":2021},
  {"title":"God Breathed","artist":"Kanye West","year":2021},
  {"title":"Heaven and Hell","artist":"Kanye West","year":2021},
  {"title":"Hurricane","artist":"Kanye West","year":2021},
  {"title":"Jail","artist":"Kanye West","year":2021},
  {"title":"Jail pt 2","artist":"Kanye West","year":2021},
  {"title":"Jesus Lord","artist":"Kanye West","year":2021},
  {"title":"Jesus Lord pt 2","artist":"Kanye West","year":2021},
  {"title":"Jonah","artist":"Kanye West","year":2021},
  {"title":"Junya","artist":"Kanye West","year":2021},
  {"title":"Junya pt 2","artist":"Kanye West","year":2021},
  {"title":"Keep My Spirit Alive","artist":"Kanye West","year":2021},
  {"title":"Keep My Spirit Alive pt 2","artist":"Kanye West","year":2021},
  {"title":"Life of the Party","artist":"Kanye West","year":2021},
  {"title":"Lord I Need You","artist":"Kanye West","year":2021},
  {"title":"Moon","artist":"Kanye West","year":2021},
  {"title":"Never Abandon Your Family","artist":"Kanye West","year":2021},
];

const KANYE_RELEASED_5 = [
  {"title":"New Again","artist":"Kanye West","year":2021},
  {"title":"No Child Left Behind","artist":"Kanye West","year":2021},
  {"title":"Off the Grid","artist":"Kanye West","year":2021},
  {"title":"Ok Ok","artist":"Kanye West","year":2021},
  {"title":"Ok Ok pt 2","artist":"Kanye West","year":2021},
  {"title":"Praise God","artist":"Kanye West","year":2021},
  {"title":"Pure Souls","artist":"Kanye West","year":2021},
  {"title":"Remote Control","artist":"Kanye West","year":2021},
  {"title":"Remote Control pt 2","artist":"Kanye West","year":2021},
  {"title":"Tell the Vision","artist":"Kanye West","year":2021},
  {"title":"The Brenda Song","artist":"Abstract Mindstate","year":2021},
  {"title":"Up from the Ashes","artist":"Kanye West","year":2021},
  {"title":"Broken Road","artist":"Kanye West","year":2022},
  {"title":"Burn Everything","artist":"Sean Leon","year":2022},
  {"title":"City of God","artist":"Kanye West","year":2022},
  {"title":"City of Gods","artist":"Fivio Foreign","year":2022},
  {"title":"Daylight","artist":"Vory","year":2022},
  {"title":"Dreamin of the Past","artist":"Pusha T","year":2022},
  {"title":"Eazy","artist":"The Game","year":2022},
  {"title":"First Time in a Long Time","artist":"Kanye West","year":2022},
  {"title":"Fortunate","artist":"The Game","year":2022},
  {"title":"Get Lost","artist":"Kanye West","year":2022},
  {"title":"Happy","artist":"Kanye West","year":2022},
  {"title":"Hot Shit","artist":"Cardi B","year":2022},
  {"title":"Keep It Burnin","artist":"Future","year":2022},
  {"title":"Keep the Flowers","artist":"Kanye West","year":2022},
  {"title":"Lord Lift Me Up","artist":"Kanye West","year":2022},
  {"title":"Louie Bags","artist":"Kanye West","year":2022},
  {"title":"Pablo","artist":"Kanye West","year":2022},
  {"title":"Rock N Roll","artist":"Pusha T","year":2022},
  {"title":"Scifi","artist":"Kanye West","year":2022},
  {"title":"Security","artist":"Kanye West","year":2022},
  {"title":"Someday We'll All Be Free","artist":"Kanye West","year":2022},
  {"title":"Too Easy","artist":"Kanye West","year":2022},
  {"title":"True Love","artist":"Kanye West","year":2022},
  {"title":"Use This Gospel (Remix)","artist":"DJ Khaled","year":2022},
  {"title":"We Did It","artist":"Kanye West","year":2022},
  {"title":"Concussion","artist":"Fivio Foreign","year":2023},
  {"title":"Israel","artist":"Albe Back","year":2023},
  {"title":"Oxygen","artist":"Sean Leon","year":2023},
  {"title":"530","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Act III: On God? (She Like) [Remix]","artist":"4batz","year":2024},
  {"title":"Back to Me","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Beg Forgiveness","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Believer","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Bomb","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Burn","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Can U Be","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Carnival","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Dead","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Do It","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Drunk","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Field Trip","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Forever","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Forever Rolling","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Fried","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Fuk Sumn","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Gimme a Second 2","artist":"Rich the Kid","year":2024},
  {"title":"Good (Don't Die)","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Gun to My Head","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Hoodrat","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Husband","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Isabella","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Keys to My Life","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"King","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Lifestyle","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Like That (Remix)","artist":"Future","year":2024},
  {"title":"My Soul","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"No Apologies","artist":"Consequence","year":2024},
  {"title":"No Bad News","artist":"Cordae","year":2024},
  {"title":"No Face","artist":"Ghostface Killah","year":2024},
  {"title":"Paid","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Paperwork","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Plain Jane","artist":"Rich the Kid","year":2024},
  {"title":"Problematic","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Promotion","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"River","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Say Less","artist":"Childish Gambino","year":2024},
  {"title":"Sky City","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Slide","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Stand United","artist":"French Montana","year":2024},
  {"title":"Stars","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Take Off Your Dress","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Talking","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Time Moving Slow","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Trinity 205","artist":"Albe Back","year":2024},
  {"title":"Vultures","artist":"Kanye West & Ty Dolla $ign","year":2024},
  {"title":"Where They At","artist":"French Montana","year":2024},
  {"title":"530","artist":"Kanye West","year":2025},
  {"title":"Beauty and the Beast","artist":"Kanye West","year":2025},
  {"title":"Burn Everything","artist":"Kanye West","year":2025},
  {"title":"City of Chi","artist":"Kanye West","year":2025},
  {"title":"Damn","artist":"Kanye West","year":2025},
  {"title":"Jesse","artist":"Kanye West","year":2025},
  {"title":"Last Breath","artist":"Kanye West","year":2025},
  {"title":"Lonely Roads Still Go to Sunshine","artist":"Kanye West","year":2025},
  {"title":"Losing Your Mind","artist":"Kanye West","year":2025},
  {"title":"Maintenance","artist":"Kanye West","year":2025},
  {"title":"Mr Miyagi","artist":"Kanye West","year":2025},
  {"title":"People Like Me","artist":"King Combs","year":2025},
];

const KANYE_RELEASED_6 = [
  {"title":"Preacher Man","artist":"Kanye West","year":2025},
  {"title":"Suzy","artist":"Kanye West","year":2025},
  {"title":"Tina","artist":"The Game","year":2025},
  {"title":"Wheels Fall Off","artist":"Ty Dolla $ign","year":2025},
  {"title":"All the Love","artist":"Kanye West","year":2026},
  {"title":"Anything Is Possible","artist":"Hass","year":2026},
  {"title":"Big Brothers","artist":"Hass","year":2026},
  {"title":"Bully","artist":"Kanye West","year":2026},
  {"title":"Circles","artist":"Kanye West","year":2026},
  {"title":"Don't Kill the Party","artist":"Ty Dolla $ign","year":2026},
  {"title":"Father","artist":"Kanye West","year":2026},
  {"title":"God's In Control","artist":"Hass","year":2026},
  {"title":"Highs and Lows","artist":"Kanye West","year":2026},
  {"title":"I Can't Wait","artist":"Kanye West","year":2026},
  {"title":"King","artist":"Kanye West","year":2026},
  {"title":"Mama's Favorite","artist":"Kanye West","year":2026},
  {"title":"Mission Control","artist":"Kanye West","year":2026},
  {"title":"No Competition","artist":"CyHi the Prynce","year":2026},
  {"title":"OK","artist":"Kanye West","year":2026},
  {"title":"Punch Drunk","artist":"Kanye West","year":2026},
  {"title":"Sisters and Brothers","artist":"Kanye West","year":2026},
  {"title":"This a Must","artist":"Kanye West","year":2026},
  {"title":"This One Here","artist":"Kanye West","year":2026},
  {"title":"Unlocked","artist":"French Montana","year":2026},
  {"title":"Whatever Works","artist":"Kanye West","year":2026},
  {"title":"White Lines","artist":"Kanye West","year":2026},
];

const KANYE_ARCHIVE_1 = [
  {"title":"187th","artist":"Kanye West","year":1996,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Take a Step Back","artist":"Kanye West","year":1996,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"All I Need","artist":"The Go Getters","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Fight with the Best","artist":"Kanye West","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Ghetto Senorita","artist":"The Go Getters","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Let Em In","artist":"The Go Getters","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Mind Yo Business","artist":"The Go Getters","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Nothin's Gonna Stop Me","artist":"Kanye West","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"On 10 in a Benz","artist":"Kanye West","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Uh Oh!","artist":"The Go Getters","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"World Record Holders","artist":"The Go Getters","year":1999,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Ain't No Money","artist":"Kanye West","year":2000,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Baby's Coming","artist":"Kanye West","year":2000,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Dream Come True","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Family Business (2001 Demo)","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Gotta Pose","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Have It Your Way","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Hey Mama (Original Version)","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Home (Windy)","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"I Met Oprah","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"I Need to Know","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Jesus Walks (Original Version)","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Know the Game","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Never Letting Go (The Stalker Song)","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Out of Your Mind","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Wow","artist":"Kanye West","year":2001,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"A Million Freestyle","artist":"Kanye West","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Come Back for You Freestyle","artist":"Kanye West","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Drop Dead Gorgeous","artist":"Kanye West","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"My Way","artist":"Kanye West","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"The Good, The Bad, The Ugly","artist":"Kanye West","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"We Can't Tell","artist":"Kanye West","year":2002,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"'03 Til Infinity","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"03 Electric Relaxation","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"18 Years","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"All Falls Down (OG)","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Apologize","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Arguing","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Bonnie & Clyde Freestyle","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Breathe In Breathe Out (OG)","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Changing Lanes","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Digital Thugz","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Doing Fine","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Drug Dealin'","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Excuse Me Miss Again (Remix)","artist":"Jay-Z","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Freewest","artist":"Freeway","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Get Em High (OG)","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Girls, Girls, Girls (Remix)","artist":"Jay-Z","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Gossip Files","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Half Price","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Improvise","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Keep the Receipt","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Last Night","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Livin' In A Movie","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"My Girlfriend","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Never Let Me Down (OG)","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Olskoolicegre","artist":"Olskool Ice-Gre","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Out the Game","artist":"Consequence","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Overreact","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Peace","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Poppin' Tags (Remix)","artist":"Jay-Z","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Self Conscious","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"The Roc In Here","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Together They're Tens","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Two Words (OG)","artist":"Kanye West","year":2003,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"03 'til Infinity","artist":"Consequence","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Better Than Yours","artist":"Kanye West","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Call Some Hoes","artist":"Chamillionaire","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Getting Out the Game","artist":"Consequence","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"I See Now","artist":"Consequence","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Keep the Receipt","artist":"Ol' Dirty Bastard","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Knock Knock (Remix)","artist":"Monica","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"No More for Me","artist":"Kanye West","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Self Conscious (Poetry Style)","artist":"Kanye West","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"So Soulful","artist":"Consequence","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Stand Up (Remix)","artist":"Ludacris","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Take It as a Loss","artist":"Consequence","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Through the Wire (Remix)","artist":"Kanye West","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Throw Ya Hands","artist":"Kanye West","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Turn Ya Self In","artist":"Consequence","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Wack Niggaz","artist":"Consequence","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"You","artist":"Kanye West","year":2004,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Bittersweet","artist":"Kanye West","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Born To Lose","artist":"Kanye West","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Crack Music (OG)","artist":"Kanye West","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Crack Music (Poetry Style)","artist":"Kanye West","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Gone (OG)","artist":"Kanye West","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Hold Me","artist":"Mashonda","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"It's Alright","artist":"Kanye West","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Jesus Walks (Remix)","artist":"Kanye West","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Promised Land Pt. 1","artist":"Kanye West","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Touch It","artist":"Kanye West","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"We Don't Care (Reprise)","artist":"Kanye West","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"You Again","artist":"Kanye West","year":2005,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Piano (Freestyle)","artist":"Kanye West","year":2006,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Story Begins","artist":"Kanye West","year":2006,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Take It As A Loss","artist":"Kanye West","year":2006,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"We Can Make It Betta","artist":"Kanye West","year":2006,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Building","artist":"Kanye West","year":2007,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Everything I've Got","artist":"Kanye West","year":2007,"catalogStatus":"archive","previewUnavailable":true},
];

const KANYE_ARCHIVE_2 = [
  {"title":"Goodbye","artist":"Kanye West","year":2007,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Thank God","artist":"Kanye West","year":2007,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Throw Some D's (Remix)","artist":"Kanye West","year":2007,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Us Placers","artist":"Child Rebel Soldier","year":2007,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Young Folks","artist":"Kanye West","year":2007,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Anyway","artist":"Kanye West","year":2008,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Diamonds & Dollars","artist":"Kanye West","year":2008,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Everything (The Diddy Song)","artist":"Kanye West","year":2008,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Hot Sauce","artist":"Kanye West","year":2008,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Sky High","artist":"Kanye West","year":2008,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"What It Is","artist":"Kanye West","year":2008,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Don't Stop!","artist":"Child Rebel Soldier","year":2009,"catalogStatus":"archive","previewUnavailable":true},
  {"title":"Glenwood","artist":"Big Sean","year":2009,"catalogStatus":"archive","previewUnavailable":true},
];

const KANYE_UNRELEASED_1 = [
  {"title":"All Of The Lights (Remix)","artist":"Kanye West","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Devil In A New Dress (Remix)","artist":"Kanye West","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Flashing Lights 2","artist":"Kanye West","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Holding Me Back","artist":"Kanye West","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"I Am A New Man","artist":"Kanye West","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Living So Italian","artist":"Kanye West","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Mama's Boyfriend","artist":"Kanye West","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Pure","artist":"Kanye West","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"See Me Again","artist":"Kanye West","year":2010,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"All The Time","artist":"Kanye West","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Awesome","artist":"Kanye West","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"No No No No","artist":"Kanye West","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Runnin Through My Dreams","artist":"Kanye West","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Whole Lifetime","artist":"Kanye West","year":2011,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Espresso","artist":"Kanye West","year":2012,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Fall Out of Heaven","artist":"Kanye West","year":2012,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Get Too High","artist":"Kanye West","year":2012,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"I Am Not Home","artist":"Kanye West","year":2012,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Oh My God","artist":"Kanye West","year":2012,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"To The Roof","artist":"Kanye West","year":2012,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Why Does Summer Have To End","artist":"Kanye West","year":2012,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Why Feel Bad","artist":"Kanye West","year":2012,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"After You","artist":"Kanye West","year":2013,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Black Skinhead (DJ Mano Remix)","artist":"Kanye West","year":2013,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Black Skinhead (Remix)","artist":"Kanye West","year":2013,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Creep Theme","artist":"Kanye West","year":2013,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Cruel Winter","artist":"Kanye West","year":2013,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"I Feel Like That","artist":"Kanye West","year":2013,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Lost Bicycle","artist":"Kanye West","year":2013,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"No Rules","artist":"Kanye West","year":2013,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"One I Love","artist":"Kanye West","year":2013,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Team Good","artist":"Kanye West","year":2013,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Where Are We","artist":"Kanye West","year":2013,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"411","artist":"Kanye West","year":2014,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"God Level","artist":"Kanye West","year":2014,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Hold Me Close","artist":"Kanye West","year":2014,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"It's Only Right","artist":"Kanye West","year":2014,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Keahole","artist":"Kanye West","year":2014,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Mrs. Misery","artist":"Kanye West","year":2014,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Rule the World","artist":"Kanye West","year":2014,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"The World","artist":"Kanye West","year":2014,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"You Ain't No Model","artist":"Kanye West","year":2014,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"All Day (Kendrick Lamar Version)","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Bad Night","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Can U Be","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Deja Vu","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Go Pro","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"High Life","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Mass Appeal","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Mitus Touch","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Motivated","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Never Let Me Go","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Nina Chop","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Only","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Prayer","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Southside Serenade","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"STAR TIME","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"The Mall","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"When I See It","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Woke Up","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Wolves (OG)","artist":"Kanye West","year":2015,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Damn Come On","artist":"Kanye West","year":2016,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Father Stretch My Hands, Pt. 1 (Remix)","artist":"Kanye West","year":2016,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Hold Tight","artist":"Kanye West","year":2016,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"In Abundance","artist":"Kanye West","year":2016,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"New Angels","artist":"Kanye West","year":2016,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"No Reason","artist":"Kanye West","year":2016,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Panda (Remix)","artist":"Kanye West","year":2016,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Survive","artist":"Kanye West","year":2016,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"The Mind Is Powerful","artist":"Kanye West","year":2016,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Zulu","artist":"Kanye West","year":2016,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Jealous","artist":"Kanye West","year":2017,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Precon","artist":"Kanye West","year":2017,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Sail","artist":"Kanye West","year":2017,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"The Garden","artist":"Kanye West","year":2017,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"124th","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"AC4","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Alien","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"All Blue Don C's","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Baby Mama","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Bitches Do Voodoo","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Black Men Don't Cheat","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Bottom Line","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Brothers","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Bye Bye Baby","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Cash To Burn","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Chakras","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Christ","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"City In The Sky","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Clouted Up","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Color 1","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Devil's Watchin","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"DJ Khaled's Son","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"End of It","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Ever Bryan","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Follow The Light","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Gun Or God","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Homestead","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"House Party","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Hurricane (OG)","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
];

const KANYE_UNRELEASED_2 = [
  {"title":"ISOTONER","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"J.J. What","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Jam 1","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Jam 11","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Jam 14","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Jam 15","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Jam 16","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Jam 17","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Jam 19","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Jam 5","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Jam 8","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Last Name","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Law of Attraction","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Let It Go","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Like The Internet","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Lovely","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Make Cap","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Moonlight","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Mrs. Robinson","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Music Is Above You","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"NEW BODY","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"No Problem","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Off The Meds","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"OOPS (Remix)","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Pillow Talk","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Robinhood","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Shoot It","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Simulation Baptize","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Sisters and Brothers","artist":"Pusha T","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Skeletons","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Sky City","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Souleros","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Tap In","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"The Storm","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Thirty Mile Zone","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"We Free (Interlude)","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"We Got Love","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Welcome To UCLA","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Yeezy My","artist":"Kanye West","year":2018,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"12,000 Acres","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"All Dreams Real","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Bad Little Darling","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Bound 3","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Cuban Link","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Daniel Is Troubled","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Don't Give Up","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Downtown Love","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Echelon","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Finding Us","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Glory","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Healing","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"I Kill For Fun","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"LA Monster","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Me Too","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"NY Dreams","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Oh Yeah","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Ozark","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Photo","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Problem","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Redo","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Skurrr","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Soul Children","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"This Is The Glory","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Through The Valley","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Tulsa","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"WAKE THE DEAD","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Wakey Wakey","artist":"Kanye West","year":2019,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Best Day","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Big Champ","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Blood Of The Lamb","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Change My State Of Mind","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"City of Lost Angels","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Codeine","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Crash Landing","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Eternal Life","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Everything","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Headshot","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Heaven And Earth","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Hold the Line","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"I Can't Complain","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"I Feel Terrific","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"In God's Country","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Karate Kid","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Let The Spirit Go Wild","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Made It","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Palm Springs","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"This Is God's Test","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Up From The Ashes (Remix)","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Welcome To My Life","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"With Child","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"You Was Right","artist":"Kanye West","year":2020,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"All These Friends Of Mine","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Can't Get Over Me","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"DEPRESSION RELIEF","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Don't Let Your Guard Down","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"FREEDOM","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"FUNNY","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"God Got Me","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"HOSTAGES","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"I'm Here For It","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
];

const KANYE_UNRELEASED_3 = [
  {"title":"Judo","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Junya (Remix)","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"LET GO","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Livin' It Up","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Never Lose","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Ninja","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Petals","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Run It Up","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Talk To Me","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"WE MADE IT THIS FAR","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Where Do We Go","artist":"Kanye West","year":2021,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Addicted","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"ALL IN LOVE","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"And They Came Back","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"ATLANTIS","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"BOBBY DIGITAL","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Can You Feel It","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Candyland","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Chingy","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Church","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"CHURCH GIRL","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Donda Prayer","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"For Once In My Life","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"FOR THE CHILDREN","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"GYPSY","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"HAPPY BIRTHDAY","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"HEAVEN","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Hold Up, Get Up","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"HOW COULD U","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Let It In","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"LEVELING UP","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"LIFESIZE","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"LOVE LOVE LOVE","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Love Me Three","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Magic","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"My Year","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"NEBRASKA","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"NOT INCLUSIVE","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Powder","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Quiet","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Rest Of Your Life","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"See The Unseen","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Spiky","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"STOP LOOKING FOR THIS","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"SUNDAY","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Survived","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Through The High Wire","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"TRAVELLER","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"WE LOVE YOU","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"What I Would Have Said at Virgil's Funeral","artist":"Kanye West","year":2022,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"BACK OUTSIDE","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Benz Freestyle 1","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"BLOCK THE PAIN AWAY","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"CITY UNDERGROUND","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"EASY COME EASY GO","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"EVERYBODY","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"FEAR","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"For Sure","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"FOREVER","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"I Forget To Breathe","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"IMAGINE DAT","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"LOVE AGAIN","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"LOVE ME THE MOST","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Lucifer","artist":"CyHi the Prynce","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"MATTHEW","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"MY GUT","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"NEXT TIME","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"NICE TO MEET YOU","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"NOBODY FLEW HER OUT","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"PEACE AND QUIET","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"PRAY","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"PUSSY COST MONEY","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"REAL HATERS","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"SO SOON","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"THE CROSS","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"WAY IT IS","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"WHAT AM I MISSING","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"WORSHIP","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"YE24 (skit)","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Zero","artist":"Kanye West","year":2023,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"AFTER LYFE","artist":"Kanye West","year":2024,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"BACKEND","artist":"Kanye West","year":2024,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"FORTUNE AND FAME","artist":"Kanye West","year":2024,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"IGNORING MY OBESITY","artist":"Kanye West","year":2024,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"NIFTY","artist":"Kanye West","year":2024,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"NIGHTS ON THE MOON","artist":"Kanye West","year":2024,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"PAY PER VIEW","artist":"Kanye West","year":2024,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Say Less","artist":"Kanye West","year":2024,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"THIRSTY","artist":"Kanye West","year":2024,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"THROW AWAY","artist":"Kanye West","year":2024,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"YE ABOUT MINE","artist":"Kanye West","year":2024,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"40 Nights","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"60 MILES","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"BIANCA","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"BULLETPROOF","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Crack Music 2","artist":"The Game","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"CRAZZZEEE","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"DRUGS GOT ME NUMB","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"FADED","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"FREAK","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
];

const KANYE_UNRELEASED_4 = [
  {"title":"Free Suge","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Git it All","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"GO","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"HAVE TO LEARN","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"JESUS","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"LIL DEMON (Remix)","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Magic Don Juan (Remix)","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"MIRRORS","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"MIXED EMOTIONS (Remix)","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"NITROUS","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"PERFECT WORLD","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"RED HOOD","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"SAY IT (Remix)","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"SHE LOVES YE","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"THE KING OF SOUL","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"Tina","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"TOOK MY KIDS","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"UNCLE","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"VIRGIL","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"WHAT HAPPENED TO US","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
  {"title":"YOU WILL","artist":"Kanye West","year":2025,"catalogStatus":"unreleased","previewUnavailable":true},
];

export const KANYE_SONGS = [
  ...KANYE_RELEASED_1,
  ...KANYE_RELEASED_2,
  ...KANYE_RELEASED_3,
  ...KANYE_RELEASED_4,
  ...KANYE_RELEASED_5,
  ...KANYE_RELEASED_6,
  ...KANYE_ARCHIVE_1,
  ...KANYE_ARCHIVE_2,
  ...KANYE_UNRELEASED_1,
  ...KANYE_UNRELEASED_2,
  ...KANYE_UNRELEASED_3,
  ...KANYE_UNRELEASED_4,
];
