// Built-in decks, installed once per browser (deleting one keeps it deleted).
// Years are original release years — the game trusts these, not iTunes.
// Previews resolve lazily via itunes.js on first play.

const STARTER_SONGS = [
  { title: 'Good Vibrations', artist: 'The Beach Boys', year: 1966 },
  { title: 'Respect', artist: 'Aretha Franklin', year: 1967 },
  { title: 'Hey Jude', artist: 'The Beatles', year: 1968 },
  { title: 'Superstition', artist: 'Stevie Wonder', year: 1972 },
  { title: 'Bohemian Rhapsody', artist: 'Queen', year: 1975 },
  { title: 'Dancing Queen', artist: 'ABBA', year: 1976 },
  { title: "Stayin' Alive", artist: 'Bee Gees', year: 1977 },
  { title: 'Billie Jean', artist: 'Michael Jackson', year: 1983 },
  { title: 'Every Breath You Take', artist: 'The Police', year: 1983 },
  { title: 'Take On Me', artist: 'a-ha', year: 1985 },
  { title: "Livin' on a Prayer", artist: 'Bon Jovi', year: 1986 },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
  { title: 'Like a Prayer', artist: 'Madonna', year: 1989 },
  { title: 'Smells Like Teen Spirit', artist: 'Nirvana', year: 1991 },
  { title: 'Wonderwall', artist: 'Oasis', year: 1995 },
  { title: 'No Scrubs', artist: 'TLC', year: 1999 },
  { title: 'I Want It That Way', artist: 'Backstreet Boys', year: 1999 },
  { title: 'Lose Yourself', artist: 'Eminem', year: 2002 },
  { title: 'Crazy in Love', artist: 'Beyoncé', year: 2003 },
  { title: 'Hey Ya!', artist: 'OutKast', year: 2003 },
  { title: 'Seven Nation Army', artist: 'The White Stripes', year: 2003 },
  { title: 'Toxic', artist: 'Britney Spears', year: 2004 },
  { title: 'Mr. Brightside', artist: 'The Killers', year: 2004 },
  { title: "Hips Don't Lie", artist: 'Shakira', year: 2006 },
  { title: 'Umbrella', artist: 'Rihanna', year: 2007 },
  { title: 'Poker Face', artist: 'Lady Gaga', year: 2008 },
  { title: 'Rolling in the Deep', artist: 'Adele', year: 2010 },
  { title: 'Get Lucky', artist: 'Daft Punk', year: 2013 },
  { title: 'Uptown Funk', artist: 'Mark Ronson', year: 2014 },
  { title: 'Hotline Bling', artist: 'Drake', year: 2015 },
  { title: 'Blinding Lights', artist: 'The Weeknd', year: 2019 },
  { title: 'bad guy', artist: 'Billie Eilish', year: 2019 },
  { title: 'Old Town Road', artist: 'Lil Nas X', year: 2019 },
  { title: 'Levitating', artist: 'Dua Lipa', year: 2020 },
  { title: 'As It Was', artist: 'Harry Styles', year: 2022 },
  { title: 'Flowers', artist: 'Miley Cyrus', year: 2023 },
  { title: 'Espresso', artist: 'Sabrina Carpenter', year: 2024 },
  { title: 'Not Like Us', artist: 'Kendrick Lamar', year: 2024 },
];

const RAP_SONGS = [
  { title: "Rapper's Delight", artist: 'The Sugarhill Gang', year: 1979 },
  { title: 'The Message', artist: 'Grandmaster Flash & The Furious Five', year: 1982 },
  { title: 'Walk This Way', artist: 'Run-DMC', year: 1986 },
  { title: 'Push It', artist: 'Salt-N-Pepa', year: 1987 },
  { title: 'Straight Outta Compton', artist: 'N.W.A.', year: 1988 },
  { title: 'Fight the Power', artist: 'Public Enemy', year: 1989 },
  { title: "U Can't Touch This", artist: 'MC Hammer', year: 1990 },
  { title: 'Summertime', artist: 'DJ Jazzy Jeff & The Fresh Prince', year: 1991 },
  { title: "Nuthin' but a 'G' Thang", artist: 'Dr. Dre', year: 1992 },
  { title: 'It Was a Good Day', artist: 'Ice Cube', year: 1992 },
  { title: 'C.R.E.A.M.', artist: 'Wu-Tang Clan', year: 1993 },
  { title: 'Juicy', artist: 'The Notorious B.I.G.', year: 1994 },
  { title: 'Regulate', artist: 'Warren G', year: 1994 },
  { title: 'California Love', artist: '2Pac', year: 1995 },
  { title: 'Hypnotize', artist: 'The Notorious B.I.G.', year: 1997 },
  { title: 'Mo Money Mo Problems', artist: 'The Notorious B.I.G.', year: 1997 },
  { title: 'Hard Knock Life (Ghetto Anthem)', artist: 'JAY-Z', year: 1998 },
  { title: 'My Name Is', artist: 'Eminem', year: 1999 },
  { title: 'Still D.R.E.', artist: 'Dr. Dre', year: 1999 },
  { title: 'The Real Slim Shady', artist: 'Eminem', year: 2000 },
  { title: 'Ms. Jackson', artist: 'OutKast', year: 2000 },
  { title: 'Hot in Herre', artist: 'Nelly', year: 2002 },
  { title: 'Lose Yourself', artist: 'Eminem', year: 2002 },
  { title: 'In da Club', artist: '50 Cent', year: 2003 },
  { title: '99 Problems', artist: 'JAY-Z', year: 2004 },
  { title: "Drop It Like It's Hot", artist: 'Snoop Dogg', year: 2004 },
  { title: 'Gold Digger', artist: 'Kanye West', year: 2005 },
  { title: 'Crank That (Soulja Boy)', artist: 'Soulja Boy', year: 2007 },
  { title: 'Lollipop', artist: 'Lil Wayne', year: 2008 },
  { title: 'Empire State of Mind', artist: 'JAY-Z', year: 2009 },
  { title: 'Black and Yellow', artist: 'Wiz Khalifa', year: 2010 },
  { title: 'Started From the Bottom', artist: 'Drake', year: 2013 },
  { title: 'Alright', artist: 'Kendrick Lamar', year: 2015 },
  { title: 'Bad and Boujee', artist: 'Migos', year: 2016 },
  { title: 'HUMBLE.', artist: 'Kendrick Lamar', year: 2017 },
  { title: 'Bodak Yellow', artist: 'Cardi B', year: 2017 },
  { title: 'SICKO MODE', artist: 'Travis Scott', year: 2018 },
  { title: "God's Plan", artist: 'Drake', year: 2018 },
  { title: 'The Box', artist: 'Roddy Ricch', year: 2019 },
  { title: 'INDUSTRY BABY', artist: 'Lil Nas X', year: 2021 },
  { title: 'First Class', artist: 'Jack Harlow', year: 2022 },
  { title: 'Not Like Us', artist: 'Kendrick Lamar', year: 2024 },
];

const POP_SONGS = [
  { title: 'I Want to Hold Your Hand', artist: 'The Beatles', year: 1963 },
  { title: 'Sugar, Sugar', artist: 'The Archies', year: 1969 },
  { title: 'ABC', artist: 'The Jackson 5', year: 1970 },
  { title: 'Crocodile Rock', artist: 'Elton John', year: 1972 },
  { title: 'Mamma Mia', artist: 'ABBA', year: 1975 },
  { title: 'I Will Survive', artist: 'Gloria Gaynor', year: 1978 },
  { title: 'Physical', artist: 'Olivia Newton-John', year: 1981 },
  { title: 'Girls Just Want to Have Fun', artist: 'Cyndi Lauper', year: 1983 },
  { title: 'Like a Virgin', artist: 'Madonna', year: 1984 },
  { title: 'Wake Me Up Before You Go-Go', artist: 'Wham!', year: 1984 },
  { title: 'When Doves Cry', artist: 'Prince', year: 1984 },
  { title: 'I Wanna Dance with Somebody (Who Loves Me)', artist: 'Whitney Houston', year: 1987 },
  { title: 'Vogue', artist: 'Madonna', year: 1990 },
  { title: 'End of the Road', artist: 'Boyz II Men', year: 1992 },
  { title: 'Wannabe', artist: 'Spice Girls', year: 1996 },
  { title: 'MMMBop', artist: 'Hanson', year: 1997 },
  { title: '...Baby One More Time', artist: 'Britney Spears', year: 1998 },
  { title: 'Genie in a Bottle', artist: 'Christina Aguilera', year: 1999 },
  { title: 'Bye Bye Bye', artist: '*NSYNC', year: 2000 },
  { title: "Can't Get You Out of My Head", artist: 'Kylie Minogue', year: 2001 },
  { title: 'Complicated', artist: 'Avril Lavigne', year: 2002 },
  { title: 'Since U Been Gone', artist: 'Kelly Clarkson', year: 2004 },
  { title: 'Hollaback Girl', artist: 'Gwen Stefani', year: 2005 },
  { title: 'SexyBack', artist: 'Justin Timberlake', year: 2006 },
  { title: 'Single Ladies (Put a Ring on It)', artist: 'Beyoncé', year: 2008 },
  { title: 'I Gotta Feeling', artist: 'The Black Eyed Peas', year: 2009 },
  { title: 'TiK ToK', artist: 'Kesha', year: 2009 },
  { title: 'Firework', artist: 'Katy Perry', year: 2010 },
  { title: 'Someone Like You', artist: 'Adele', year: 2011 },
  { title: 'Call Me Maybe', artist: 'Carly Rae Jepsen', year: 2012 },
  { title: 'Shake It Off', artist: 'Taylor Swift', year: 2014 },
  { title: 'Sorry', artist: 'Justin Bieber', year: 2015 },
  { title: "Can't Stop the Feeling!", artist: 'Justin Timberlake', year: 2016 },
  { title: 'Shape of You', artist: 'Ed Sheeran', year: 2017 },
  { title: 'Havana', artist: 'Camila Cabello', year: 2017 },
  { title: 'thank u, next', artist: 'Ariana Grande', year: 2018 },
  { title: 'Watermelon Sugar', artist: 'Harry Styles', year: 2019 },
  { title: 'drivers license', artist: 'Olivia Rodrigo', year: 2021 },
  { title: 'Anti-Hero', artist: 'Taylor Swift', year: 2022 },
  { title: 'About Damn Time', artist: 'Lizzo', year: 2022 },
  { title: 'greedy', artist: 'Tate McRae', year: 2023 },
  { title: 'Good Luck, Babe!', artist: 'Chappell Roan', year: 2024 },
  { title: 'Birds of a Feather', artist: 'Billie Eilish', year: 2024 },
];

export const SEED_DECKS = [
  { key: 'starter', name: 'Starter deck (replace with your taste!)', songs: STARTER_SONGS },
  { key: 'rap', name: 'Rap & Hip-Hop', songs: RAP_SONGS },
  { key: 'pop', name: 'Pop Through the Decades', songs: POP_SONGS },
];
