// Starter deck: well-known hits spanning seven decades. Demo content —
// the whole point of the app is replacing this with your own decks.
// Years are original release years. Previews resolve lazily via itunes.js.
export const SEED_SONGS = [
  { title: 'Good Vibrations', artist: 'The Beach Boys', year: 1966 },
  { title: 'Respect', artist: 'Aretha Franklin', year: 1967 },
  { title: 'Hey Jude', artist: 'The Beatles', year: 1968 },
  { title: 'Superstition', artist: 'Stevie Wonder', year: 1972 },
  { title: 'Bohemian Rhapsody', artist: 'Queen', year: 1975 },
  { title: 'Dancing Queen', artist: 'ABBA', year: 1976 },
  { title: "Stayin' Alive", artist: 'Bee Gees', year: 1977 },
  { title: 'Billie Jean', artist: 'Michael Jackson', year: 1983 },
  { title: 'Every Breath You Take', artist: 'The Police', year: 1983 },
  { title: 'Take On Me', artist: 'a-ha', year: 1985 },
  { title: "Livin' on a Prayer", artist: 'Bon Jovi', year: 1986 },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
  { title: 'Like a Prayer', artist: 'Madonna', year: 1989 },
  { title: 'Smells Like Teen Spirit', artist: 'Nirvana', year: 1991 },
  { title: 'Wonderwall', artist: 'Oasis', year: 1995 },
  { title: 'No Scrubs', artist: 'TLC', year: 1999 },
  { title: 'I Want It That Way', artist: 'Backstreet Boys', year: 1999 },
  { title: 'Lose Yourself', artist: 'Eminem', year: 2002 },
  { title: 'Crazy in Love', artist: 'Beyoncé', year: 2003 },
  { title: 'Hey Ya!', artist: 'OutKast', year: 2003 },
  { title: 'Seven Nation Army', artist: 'The White Stripes', year: 2003 },
  { title: 'Toxic', artist: 'Britney Spears', year: 2004 },
  { title: 'Mr. Brightside', artist: 'The Killers', year: 2004 },
  { title: "Hips Don't Lie", artist: 'Shakira', year: 2006 },
  { title: 'Umbrella', artist: 'Rihanna', year: 2007 },
  { title: 'Poker Face', artist: 'Lady Gaga', year: 2008 },
  { title: 'Rolling in the Deep', artist: 'Adele', year: 2010 },
  { title: 'Get Lucky', artist: 'Daft Punk', year: 2013 },
  { title: 'Uptown Funk', artist: 'Mark Ronson', year: 2014 },
  { title: 'Hotline Bling', artist: 'Drake', year: 2015 },
  { title: 'Blinding Lights', artist: 'The Weeknd', year: 2019 },
  { title: 'bad guy', artist: 'Billie Eilish', year: 2019 },
  { title: 'Old Town Road', artist: 'Lil Nas X', year: 2019 },
  { title: 'Levitating', artist: 'Dua Lipa', year: 2020 },
  { title: 'As It Was', artist: 'Harry Styles', year: 2022 },
  { title: 'Flowers', artist: 'Miley Cyrus', year: 2023 },
  { title: 'Espresso', artist: 'Sabrina Carpenter', year: 2024 },
  { title: 'Not Like Us', artist: 'Kendrick Lamar', year: 2024 },
];
