// Built-in decks, installed once per browser (deleting one keeps it deleted).
// Years are original release years. The game trusts these, not iTunes.
// Previews resolve lazily via itunes.js/deezer.js on first play.
//
// Bumping a deck's `version` after adding songs makes ensureSeedDecks top up
// already-installed copies (new songs appended, user edits/ratings preserved).

const STARTER_SONGS = [
  { title: 'Good Vibrations', artist: 'The Beach Boys', year: 1966 },
  { title: 'Respect', artist: 'Aretha Franklin', year: 1967 },
  { title: 'Hey Jude', artist: 'The Beatles', year: 1968 },
  { title: 'I Heard It Through the Grapevine', artist: 'Marvin Gaye', year: 1968 },
  { title: 'Sweet Caroline', artist: 'Neil Diamond', year: 1969 },
  { title: 'Superstition', artist: 'Stevie Wonder', year: 1972 },
  { title: 'Bohemian Rhapsody', artist: 'Queen', year: 1975 },
  { title: 'Dancing Queen', artist: 'ABBA', year: 1976 },
  { title: "Stayin' Alive", artist: 'Bee Gees', year: 1977 },
  { title: 'September', artist: 'Earth, Wind & Fire', year: 1978 },
  { title: 'Y.M.C.A.', artist: 'Village People', year: 1978 },
  { title: "Don't Stop Believin'", artist: 'Journey', year: 1981 },
  { title: 'Eye of the Tiger', artist: 'Survivor', year: 1982 },
  { title: 'Africa', artist: 'Toto', year: 1982 },
  { title: 'Billie Jean', artist: 'Michael Jackson', year: 1983 },
  { title: 'Every Breath You Take', artist: 'The Police', year: 1983 },
  { title: 'Footloose', artist: 'Kenny Loggins', year: 1984 },
  { title: 'Take On Me', artist: 'a-ha', year: 1985 },
  { title: "Livin' on a Prayer", artist: 'Bon Jovi', year: 1986 },
  { title: 'Never Gonna Give You Up', artist: 'Rick Astley', year: 1987 },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987 },
  { title: 'Like a Prayer', artist: 'Madonna', year: 1989 },
  { title: 'Ice Ice Baby', artist: 'Vanilla Ice', year: 1990 },
  { title: 'Smells Like Teen Spirit', artist: 'Nirvana', year: 1991 },
  { title: 'I Will Always Love You', artist: 'Whitney Houston', year: 1992 },
  { title: 'What Is Love', artist: 'Haddaway', year: 1993 },
  { title: 'Wonderwall', artist: 'Oasis', year: 1995 },
  { title: 'Barbie Girl', artist: 'Aqua', year: 1997 },
  { title: 'No Scrubs', artist: 'TLC', year: 1999 },
  { title: 'I Want It That Way', artist: 'Backstreet Boys', year: 1999 },
  { title: 'All Star', artist: 'Smash Mouth', year: 1999 },
  { title: 'In the End', artist: 'Linkin Park', year: 2000 },
  { title: 'Lose Yourself', artist: 'Eminem', year: 2002 },
  { title: 'Crazy in Love', artist: 'Beyoncé', year: 2003 },
  { title: 'Hey Ya!', artist: 'OutKast', year: 2003 },
  { title: 'Seven Nation Army', artist: 'The White Stripes', year: 2003 },
  { title: 'Toxic', artist: 'Britney Spears', year: 2004 },
  { title: 'Mr. Brightside', artist: 'The Killers', year: 2004 },
  { title: 'Yeah!', artist: 'Usher', year: 2004 },
  { title: "Hips Don't Lie", artist: 'Shakira', year: 2006 },
  { title: 'Umbrella', artist: 'Rihanna', year: 2007 },
  { title: 'Poker Face', artist: 'Lady Gaga', year: 2008 },
  { title: 'Viva la Vida', artist: 'Coldplay', year: 2008 },
  { title: 'Party in the U.S.A.', artist: 'Miley Cyrus', year: 2009 },
  { title: 'Rolling in the Deep', artist: 'Adele', year: 2010 },
  { title: 'Somebody That I Used to Know', artist: 'Gotye', year: 2011 },
  { title: 'Thrift Shop', artist: 'Macklemore & Ryan Lewis', year: 2012 },
  { title: 'Get Lucky', artist: 'Daft Punk', year: 2013 },
  { title: 'Happy', artist: 'Pharrell Williams', year: 2013 },
  { title: 'Uptown Funk', artist: 'Mark Ronson', year: 2014 },
  { title: 'Hotline Bling', artist: 'Drake', year: 2015 },
  { title: 'Shallow', artist: 'Lady Gaga & Bradley Cooper', year: 2018 },
  { title: 'Blinding Lights', artist: 'The Weeknd', year: 2019 },
  { title: 'bad guy', artist: 'Billie Eilish', year: 2019 },
  { title: 'Old Town Road', artist: 'Lil Nas X', year: 2019 },
  { title: 'Levitating', artist: 'Dua Lipa', year: 2020 },
  { title: 'Heat Waves', artist: 'Glass Animals', year: 2020 },
  { title: 'As It Was', artist: 'Harry Styles', year: 2022 },
  { title: 'Flowers', artist: 'Miley Cyrus', year: 2023 },
  { title: 'Espresso', artist: 'Sabrina Carpenter', year: 2024 },
  { title: 'Not Like Us', artist: 'Kendrick Lamar', year: 2024 },
];

const RAP_SONGS = [
  { title: "Rapper's Delight", artist: 'The Sugarhill Gang', year: 1979 },
  { title: 'The Message', artist: 'Grandmaster Flash & The Furious Five', year: 1982 },
  { title: 'Walk This Way', artist: 'Run-DMC', year: 1986 },
  { title: 'Push It', artist: 'Salt-N-Pepa', year: 1987 },
  { title: 'Straight Outta Compton', artist: 'N.W.A.', year: 1988 },
  { title: 'Fight the Power', artist: 'Public Enemy', year: 1989 },
  { title: "U Can't Touch This", artist: 'MC Hammer', year: 1990 },
  { title: 'Summertime', artist: 'DJ Jazzy Jeff & The Fresh Prince', year: 1991 },
  { title: 'Jump', artist: 'Kris Kross', year: 1992 },
  { title: 'Baby Got Back', artist: 'Sir Mix-a-Lot', year: 1992 },
  { title: "Nuthin' but a 'G' Thang", artist: 'Dr. Dre', year: 1992 },
  { title: 'It Was a Good Day', artist: 'Ice Cube', year: 1992 },
  { title: 'C.R.E.A.M.', artist: 'Wu-Tang Clan', year: 1993 },
  { title: 'Juicy', artist: 'The Notorious B.I.G.', year: 1994 },
  { title: 'Regulate', artist: 'Warren G', year: 1994 },
  { title: "Gangsta's Paradise", artist: 'Coolio', year: 1995 },
  { title: 'California Love', artist: '2Pac', year: 1995 },
  { title: 'Hypnotize', artist: 'The Notorious B.I.G.', year: 1997 },
  { title: 'Mo Money Mo Problems', artist: 'The Notorious B.I.G.', year: 1997 },
  { title: 'Hard Knock Life (Ghetto Anthem)', artist: 'JAY-Z', year: 1998 },
  { title: 'My Name Is', artist: 'Eminem', year: 1999 },
  { title: 'Still D.R.E.', artist: 'Dr. Dre', year: 1999 },
  { title: 'The Real Slim Shady', artist: 'Eminem', year: 2000 },
  { title: 'Ms. Jackson', artist: 'OutKast', year: 2000 },
  { title: 'Ride wit Me', artist: 'Nelly', year: 2000 },
  { title: 'Izzo (H.O.V.A.)', artist: 'JAY-Z', year: 2001 },
  { title: 'Hot in Herre', artist: 'Nelly', year: 2002 },
  { title: 'Work It', artist: 'Missy Elliott', year: 2002 },
  { title: 'Lose Yourself', artist: 'Eminem', year: 2002 },
  { title: 'In da Club', artist: '50 Cent', year: 2003 },
  { title: 'Stand Up', artist: 'Ludacris', year: 2003 },
  { title: '99 Problems', artist: 'JAY-Z', year: 2004 },
  { title: "Drop It Like It's Hot", artist: 'Snoop Dogg', year: 2004 },
  { title: 'Gold Digger', artist: 'Kanye West', year: 2005 },
  { title: "Ridin'", artist: 'Chamillionaire', year: 2005 },
  { title: 'What You Know', artist: 'T.I.', year: 2006 },
  { title: 'Crank That (Soulja Boy)', artist: 'Soulja Boy', year: 2007 },
  { title: 'Stronger', artist: 'Kanye West', year: 2007 },
  { title: 'Low', artist: 'Flo Rida', year: 2007 },
  { title: 'Lollipop', artist: 'Lil Wayne', year: 2008 },
  { title: 'A Milli', artist: 'Lil Wayne', year: 2008 },
  { title: 'Empire State of Mind', artist: 'JAY-Z', year: 2009 },
  { title: 'Black and Yellow', artist: 'Wiz Khalifa', year: 2010 },
  { title: 'All of the Lights', artist: 'Kanye West', year: 2010 },
  { title: 'Swimming Pools (Drank)', artist: 'Kendrick Lamar', year: 2012 },
  { title: 'Started From the Bottom', artist: 'Drake', year: 2013 },
  { title: 'Alright', artist: 'Kendrick Lamar', year: 2015 },
  { title: 'Bad and Boujee', artist: 'Migos', year: 2016 },
  { title: 'HUMBLE.', artist: 'Kendrick Lamar', year: 2017 },
  { title: 'Bodak Yellow', artist: 'Cardi B', year: 2017 },
  { title: 'Mask Off', artist: 'Future', year: 2017 },
  { title: 'SICKO MODE', artist: 'Travis Scott', year: 2018 },
  { title: "God's Plan", artist: 'Drake', year: 2018 },
  { title: 'Going Bad', artist: 'Meek Mill', year: 2018 },
  { title: 'The Box', artist: 'Roddy Ricch', year: 2019 },
  { title: 'Savage', artist: 'Megan Thee Stallion', year: 2020 },
  { title: 'INDUSTRY BABY', artist: 'Lil Nas X', year: 2021 },
  { title: 'First Class', artist: 'Jack Harlow', year: 2022 },
  { title: 'Jimmy Cooks', artist: 'Drake', year: 2022 },
  { title: 'Lovin On Me', artist: 'Jack Harlow', year: 2023 },
  { title: 'Not Like Us', artist: 'Kendrick Lamar', year: 2024 },
];

const POP_SONGS = [
  { title: 'I Want to Hold Your Hand', artist: 'The Beatles', year: 1963 },
  { title: 'Sugar, Sugar', artist: 'The Archies', year: 1969 },
  { title: 'ABC', artist: 'The Jackson 5', year: 1970 },
  { title: 'Crocodile Rock', artist: 'Elton John', year: 1972 },
  { title: 'Mamma Mia', artist: 'ABBA', year: 1975 },
  { title: 'I Will Survive', artist: 'Gloria Gaynor', year: 1978 },
  { title: 'Physical', artist: 'Olivia Newton-John', year: 1981 },
  { title: 'Girls Just Want to Have Fun', artist: 'Cyndi Lauper', year: 1983 },
  { title: 'Karma Chameleon', artist: 'Culture Club', year: 1983 },
  { title: 'Like a Virgin', artist: 'Madonna', year: 1984 },
  { title: 'Wake Me Up Before You Go-Go', artist: 'Wham!', year: 1984 },
  { title: 'When Doves Cry', artist: 'Prince', year: 1984 },
  { title: 'I Wanna Dance with Somebody (Who Loves Me)', artist: 'Whitney Houston', year: 1987 },
  { title: 'Vogue', artist: 'Madonna', year: 1990 },
  { title: 'End of the Road', artist: 'Boyz II Men', year: 1992 },
  { title: 'Wannabe', artist: 'Spice Girls', year: 1996 },
  { title: 'MMMBop', artist: 'Hanson', year: 1997 },
  { title: '...Baby One More Time', artist: 'Britney Spears', year: 1998 },
  { title: 'Genie in a Bottle', artist: 'Christina Aguilera', year: 1999 },
  { title: "Livin' La Vida Loca", artist: 'Ricky Martin', year: 1999 },
  { title: 'Bye Bye Bye', artist: '*NSYNC', year: 2000 },
  { title: 'Oops!... I Did It Again', artist: 'Britney Spears', year: 2000 },
  { title: 'Survivor', artist: "Destiny's Child", year: 2001 },
  { title: "Can't Get You Out of My Head", artist: 'Kylie Minogue', year: 2001 },
  { title: 'Complicated', artist: 'Avril Lavigne', year: 2002 },
  { title: 'A Thousand Miles', artist: 'Vanessa Carlton', year: 2002 },
  { title: 'Since U Been Gone', artist: 'Kelly Clarkson', year: 2004 },
  { title: 'Hollaback Girl', artist: 'Gwen Stefani', year: 2005 },
  { title: 'SexyBack', artist: 'Justin Timberlake', year: 2006 },
  { title: 'Crazy', artist: 'Gnarls Barkley', year: 2006 },
  { title: 'Single Ladies (Put a Ring on It)', artist: 'Beyoncé', year: 2008 },
  { title: 'Just Dance', artist: 'Lady Gaga', year: 2008 },
  { title: 'I Gotta Feeling', artist: 'The Black Eyed Peas', year: 2009 },
  { title: 'TiK ToK', artist: 'Kesha', year: 2009 },
  { title: 'Firework', artist: 'Katy Perry', year: 2010 },
  { title: 'Someone Like You', artist: 'Adele', year: 2011 },
  { title: 'We Found Love', artist: 'Rihanna', year: 2011 },
  { title: 'Call Me Maybe', artist: 'Carly Rae Jepsen', year: 2012 },
  { title: 'Locked Out of Heaven', artist: 'Bruno Mars', year: 2012 },
  { title: 'Counting Stars', artist: 'OneRepublic', year: 2013 },
  { title: 'Shake It Off', artist: 'Taylor Swift', year: 2014 },
  { title: 'All About That Bass', artist: 'Meghan Trainor', year: 2014 },
  { title: 'Sorry', artist: 'Justin Bieber', year: 2015 },
  { title: 'Hello', artist: 'Adele', year: 2015 },
  { title: "Can't Stop the Feeling!", artist: 'Justin Timberlake', year: 2016 },
  { title: 'Cheap Thrills', artist: 'Sia', year: 2016 },
  { title: 'Shape of You', artist: 'Ed Sheeran', year: 2017 },
  { title: 'Havana', artist: 'Camila Cabello', year: 2017 },
  { title: 'New Rules', artist: 'Dua Lipa', year: 2017 },
  { title: 'thank u, next', artist: 'Ariana Grande', year: 2018 },
  { title: 'Watermelon Sugar', artist: 'Harry Styles', year: 2019 },
  { title: 'Dance Monkey', artist: 'Tones and I', year: 2019 },
  { title: 'drivers license', artist: 'Olivia Rodrigo', year: 2021 },
  { title: 'Stay', artist: 'The Kid LAROI & Justin Bieber', year: 2021 },
  { title: 'Anti-Hero', artist: 'Taylor Swift', year: 2022 },
  { title: 'About Damn Time', artist: 'Lizzo', year: 2022 },
  { title: 'greedy', artist: 'Tate McRae', year: 2023 },
  { title: 'Paint The Town Red', artist: 'Doja Cat', year: 2023 },
  { title: 'Good Luck, Babe!', artist: 'Chappell Roan', year: 2024 },
  { title: 'Birds of a Feather', artist: 'Billie Eilish', year: 2024 },
  { title: 'Please Please Please', artist: 'Sabrina Carpenter', year: 2024 },
];

const ROCK_SONGS = [
  { title: "(I Can't Get No) Satisfaction", artist: 'The Rolling Stones', year: 1965 },
  { title: 'Light My Fire', artist: 'The Doors', year: 1967 },
  { title: 'Born to Be Wild', artist: 'Steppenwolf', year: 1968 },
  { title: 'Fortunate Son', artist: 'Creedence Clearwater Revival', year: 1969 },
  { title: 'Paranoid', artist: 'Black Sabbath', year: 1970 },
  { title: 'Stairway to Heaven', artist: 'Led Zeppelin', year: 1971 },
  { title: "School's Out", artist: 'Alice Cooper', year: 1972 },
  { title: 'Free Bird', artist: 'Lynyrd Skynyrd', year: 1973 },
  { title: 'Born to Run', artist: 'Bruce Springsteen', year: 1975 },
  { title: 'Hotel California', artist: 'Eagles', year: 1976 },
  { title: 'We Will Rock You', artist: 'Queen', year: 1977 },
  { title: 'Highway to Hell', artist: 'AC/DC', year: 1979 },
  { title: 'Back In Black', artist: 'AC/DC', year: 1980 },
  { title: 'Under Pressure', artist: 'Queen & David Bowie', year: 1981 },
  { title: 'Should I Stay or Should I Go', artist: 'The Clash', year: 1982 },
  { title: 'Jump', artist: 'Van Halen', year: 1984 },
  { title: 'Born in the U.S.A.', artist: 'Bruce Springsteen', year: 1984 },
  { title: 'Running Up That Hill (A Deal with God)', artist: 'Kate Bush', year: 1985 },
  { title: 'The Final Countdown', artist: 'Europe', year: 1986 },
  { title: 'Welcome to the Jungle', artist: "Guns N' Roses", year: 1987 },
  { title: 'With or Without You', artist: 'U2', year: 1987 },
  { title: "Free Fallin'", artist: 'Tom Petty', year: 1989 },
  { title: 'Enter Sandman', artist: 'Metallica', year: 1991 },
  { title: 'Alive', artist: 'Pearl Jam', year: 1991 },
  { title: 'Under the Bridge', artist: 'Red Hot Chili Peppers', year: 1992 },
  { title: 'Loser', artist: 'Beck', year: 1993 },
  { title: 'Basket Case', artist: 'Green Day', year: 1994 },
  { title: 'Zombie', artist: 'The Cranberries', year: 1994 },
  { title: 'Semi-Charmed Life', artist: 'Third Eye Blind', year: 1997 },
  { title: 'Iris', artist: 'Goo Goo Dolls', year: 1998 },
  { title: 'All the Small Things', artist: 'blink-182', year: 1999 },
  { title: 'Kryptonite', artist: '3 Doors Down', year: 2000 },
  { title: 'How You Remind Me', artist: 'Nickelback', year: 2001 },
  { title: 'The Middle', artist: 'Jimmy Eat World', year: 2001 },
  { title: 'Last Nite', artist: 'The Strokes', year: 2001 },
  { title: 'Numb', artist: 'Linkin Park', year: 2003 },
  { title: 'American Idiot', artist: 'Green Day', year: 2004 },
  { title: 'Feel Good Inc.', artist: 'Gorillaz', year: 2005 },
  { title: 'Welcome to the Black Parade', artist: 'My Chemical Romance', year: 2006 },
  { title: 'Dani California', artist: 'Red Hot Chili Peppers', year: 2006 },
  { title: 'Sex on Fire', artist: 'Kings of Leon', year: 2008 },
  { title: 'Little Lion Man', artist: 'Mumford & Sons', year: 2009 },
  { title: 'Pumped Up Kicks', artist: 'Foster the People', year: 2010 },
  { title: 'Ho Hey', artist: 'The Lumineers', year: 2012 },
  { title: 'Radioactive', artist: 'Imagine Dragons', year: 2012 },
  { title: 'Take Me to Church', artist: 'Hozier', year: 2013 },
  { title: 'Centuries', artist: 'Fall Out Boy', year: 2014 },
  { title: 'Stressed Out', artist: 'Twenty One Pilots', year: 2015 },
  { title: 'Believer', artist: 'Imagine Dragons', year: 2017 },
  { title: 'Level of Concern', artist: 'Twenty One Pilots', year: 2020 },
];

const RNB_SONGS = [
  { title: 'Stand by Me', artist: 'Ben E. King', year: 1961 },
  { title: 'My Girl', artist: 'The Temptations', year: 1964 },
  { title: "I Can't Help Myself (Sugar Pie Honey Bunch)", artist: 'Four Tops', year: 1965 },
  { title: 'When a Man Loves a Woman', artist: 'Percy Sledge', year: 1966 },
  { title: '(You Make Me Feel Like) A Natural Woman', artist: 'Aretha Franklin', year: 1967 },
  { title: "(Sittin' On) The Dock of the Bay", artist: 'Otis Redding', year: 1968 },
  { title: 'I Want You Back', artist: 'The Jackson 5', year: 1969 },
  { title: "What's Going On", artist: 'Marvin Gaye', year: 1971 },
  { title: "Let's Stay Together", artist: 'Al Green', year: 1971 },
  { title: 'Jungle Boogie', artist: 'Kool & The Gang', year: 1973 },
  { title: 'Play That Funky Music', artist: 'Wild Cherry', year: 1976 },
  { title: 'Best of My Love', artist: 'The Emotions', year: 1977 },
  { title: 'Good Times', artist: 'Chic', year: 1979 },
  { title: 'Endless Love', artist: 'Diana Ross & Lionel Richie', year: 1981 },
  { title: 'Sexual Healing', artist: 'Marvin Gaye', year: 1982 },
  { title: 'Caribbean Queen (No More Love on the Run)', artist: 'Billy Ocean', year: 1984 },
  { title: 'Rhythm of the Night', artist: 'DeBarge', year: 1985 },
  { title: 'My Prerogative', artist: 'Bobby Brown', year: 1988 },
  { title: 'Poison', artist: 'Bell Biv DeVoe', year: 1990 },
  { title: 'Motownphilly', artist: 'Boyz II Men', year: 1991 },
  { title: 'Remember the Time', artist: 'Michael Jackson', year: 1992 },
  { title: "That's the Way Love Goes", artist: 'Janet Jackson', year: 1993 },
  { title: 'Creep', artist: 'TLC', year: 1994 },
  { title: 'This Is How We Do It', artist: 'Montell Jordan', year: 1995 },
  { title: 'No Diggity', artist: 'Blackstreet', year: 1996 },
  { title: 'Killing Me Softly With His Song', artist: 'Fugees', year: 1996 },
  { title: 'Doo Wop (That Thing)', artist: 'Ms. Lauryn Hill', year: 1998 },
  { title: 'Say My Name', artist: "Destiny's Child", year: 1999 },
  { title: 'Try Again', artist: 'Aaliyah', year: 2000 },
  { title: "Fallin'", artist: 'Alicia Keys', year: 2001 },
  { title: 'Foolish', artist: 'Ashanti', year: 2002 },
  { title: "Frontin'", artist: 'Pharrell Williams', year: 2003 },
  { title: 'Burn', artist: 'Usher', year: 2004 },
  { title: 'Be Without You', artist: 'Mary J. Blige', year: 2005 },
  { title: 'Bleeding Love', artist: 'Leona Lewis', year: 2007 },
  { title: 'Pretty Wings', artist: 'Maxwell', year: 2009 },
  { title: 'Adorn', artist: 'Miguel', year: 2012 },
  { title: 'Blurred Lines', artist: 'Robin Thicke', year: 2013 },
  { title: 'Earned It', artist: 'The Weeknd', year: 2014 },
  { title: 'Needed Me', artist: 'Rihanna', year: 2016 },
  { title: 'Redbone', artist: 'Childish Gambino', year: 2016 },
  { title: 'Best Part', artist: 'Daniel Caesar', year: 2017 },
  { title: 'Leave the Door Open', artist: 'Silk Sonic', year: 2021 },
  { title: 'Kill Bill', artist: 'SZA', year: 2022 },
  { title: 'Water', artist: 'Tyla', year: 2023 },
];

const THROWBACK_SONGS = [
  { title: 'Who Let the Dogs Out', artist: 'Baha Men', year: 2000 },
  { title: 'Drops of Jupiter', artist: 'Train', year: 2001 },
  { title: 'Get the Party Started', artist: 'P!nk', year: 2001 },
  { title: 'Sk8er Boi', artist: 'Avril Lavigne', year: 2002 },
  { title: 'Bring Me to Life', artist: 'Evanescence', year: 2003 },
  { title: "Stacy's Mom", artist: 'Fountains of Wayne', year: 2003 },
  { title: '1985', artist: 'Bowling for Soup', year: 2004 },
  { title: 'Dirty Little Secret', artist: 'The All-American Rejects', year: 2005 },
  { title: 'Beverly Hills', artist: 'Weezer', year: 2005 },
  { title: 'Photograph', artist: 'Nickelback', year: 2005 },
  { title: 'Chasing Cars', artist: 'Snow Patrol', year: 2006 },
  { title: 'Promiscuous', artist: 'Nelly Furtado', year: 2006 },
  { title: 'The Sweet Escape', artist: 'Gwen Stefani', year: 2006 },
  { title: 'Beautiful Girls', artist: 'Sean Kingston', year: 2007 },
  { title: 'I Kissed a Girl', artist: 'Katy Perry', year: 2008 },
  { title: 'Disturbia', artist: 'Rihanna', year: 2008 },
  { title: 'Fireflies', artist: 'Owl City', year: 2009 },
  { title: 'Down', artist: 'Jay Sean', year: 2009 },
  { title: 'Replay', artist: 'Iyaz', year: 2009 },
  { title: 'Dynamite', artist: 'Taio Cruz', year: 2010 },
  { title: 'Airplanes', artist: 'B.o.B', year: 2010 },
  { title: 'Just the Way You Are', artist: 'Bruno Mars', year: 2010 },
  { title: 'Party Rock Anthem', artist: 'LMFAO', year: 2011 },
  { title: 'Super Bass', artist: 'Nicki Minaj', year: 2011 },
  { title: 'Moves Like Jagger', artist: 'Maroon 5', year: 2011 },
  { title: 'Domino', artist: 'Jessie J', year: 2011 },
  { title: 'Gangnam Style', artist: 'PSY', year: 2012 },
  { title: 'Some Nights', artist: 'fun.', year: 2012 },
  { title: 'Royals', artist: 'Lorde', year: 2013 },
  { title: 'Wrecking Ball', artist: 'Miley Cyrus', year: 2013 },
  { title: 'Timber', artist: 'Pitbull', year: 2013 },
  { title: 'Rude', artist: 'MAGIC!', year: 2013 },
  { title: 'Fancy', artist: 'Iggy Azalea', year: 2014 },
  { title: 'Watch Me (Whip/Nae Nae)', artist: 'Silentó', year: 2015 },
  { title: 'Cake By the Ocean', artist: 'DNCE', year: 2015 },
  { title: 'Closer', artist: 'The Chainsmokers', year: 2016 },
  { title: 'One Dance', artist: 'Drake', year: 2016 },
  { title: 'Despacito', artist: 'Luis Fonsi', year: 2017 },
  { title: 'rockstar', artist: 'Post Malone', year: 2017 },
  { title: 'Sunflower', artist: 'Post Malone & Swae Lee', year: 2018 },
  { title: 'I Like It', artist: 'Cardi B', year: 2018 },
  { title: '7 rings', artist: 'Ariana Grande', year: 2019 },
];

export const SEED_DECKS = [
  { key: 'starter', version: 2, name: 'Starter deck (replace with your taste!)', songs: STARTER_SONGS },
  { key: 'rap', version: 2, name: 'Rap & Hip-Hop', songs: RAP_SONGS },
  { key: 'pop', version: 2, name: 'Pop Through the Decades', songs: POP_SONGS },
  { key: 'rock', version: 1, name: 'Rock Anthems', songs: ROCK_SONGS },
  { key: 'rnb', version: 1, name: 'R&B & Soul', songs: RNB_SONGS },
  { key: 'throwbacks', version: 1, name: '2000s & 2010s Throwbacks', songs: THROWBACK_SONGS },
];
